#----------------------------------------------------------------------------
# Aliases
{{alias}}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

#---------------------------------------
# Global Block

#----------------------------------------------------------------------------
# Default
{+block{GenericHost}}
ad*.
.*ads.
.ad.?.
.ad.[a-ik-z][a-oq-z].
.ad.jp.*.
.ad.???*.
.*advert*.
*banner*.
count*.
*counter.
metrics.

{-block}
adsl.
ad[udmw]*.
adbl*.
adam*.
adapt*.
adob*.
adrenaline.
adtp*.
adv[oia]*.
adventure*.
.*road*.
.olympiad*.
.*load*.
.*[epu]ad*.
county*.
countr*.
metrics.torproject.org
linuxcounter.net
adina*.
adele*.
adlibris.
.adbshell.com
.adbinstaller.com
ada*.

{+block{GenericPath}}
/(.*/)?ad(\?|/|s|v|_?(image|se?rv|box)|cycle|rotate|mentor|click|f[ra]m|script|stream|fetch|log|space)
/phpads(new)?/
/(.*/)?(ad|all|nn|db|promo(tion)?)?[-_]?banner
/(.*/)?(publicite|werbung|rekla(me|am)|annonse|maino(kset|nta|s)?/)
/.*(count|track|compteur|(?<!relo)adframe|adse?rve?|banner)(er|run)?(\?|\.(pl|cgi|exe|dll|asp|php|cpt))
/(.*/)?clicktrack
/(.*/)?(full)?pop[-_]?(up|over|under|open(er)?)?s?(/|\.)
/(.*/)?((flash)?pop|live(cnt|count(er)?)).*\.(js|php|cgi)
/openx/www/delivery/
/.*bannerid=
/.*DigiAd
/.*://ads\.
/(.*/)?piwik\.php
#
/(.*/)?images/ad-
/(.*/)?advert/
/(.*/)?textad_
/(.*/)?banner/ad_
/(.*/)?realmedia/ads/
/(.*/)?ad_server\.
/(.*/)?advertisingmodule\.
/(.*/)?swfbin/ad3-
/.*-publicite\.
.com/js/adsense
/(.*/)?oas\.js
/(.*/)?javascript/ads\.
/.*://bwp.*/search
/(.*/)?sponsored-articles/

{-block}
/.*ad(sl|v(i[cs]|o|an|ertencia|ent|.*search|erse))
/.*(lo|thre|he|d|gr|l|ro|re|squ|class(ified)?)ads
/.*account
support./(.*/)?track
/.*\.git/objects/
/.*Bugtracker
/(.*/)?pop[a-z_-]*menu
.edu
.ac.*/
.uni-*.de
.tu-*.de
.gov
.hs-*.de
.fh-*.de
.org/.*(image|banner)
cdn.popsww.com/popsapp/
ads-blocker.com/testing
.nimo.tv/(.*/)?img.webp
.redditmedia.com/(.*/)?styles/bannerBackgroundImage_

#----------------------------------------------------------------------------
# Domain
{+block{domain}}
ads.
ad.
.namequery.
.*stats*.
.*counter*.
.*meter)*.
.*adver*.
.*adca*.
.adzerk.
.affiliate.
logging.
.coinurl.
.cdn.delivery*.
.*click.
.*chart.
stc.nas.nixcdn.com
.eclick.
.innity.
.jsn.mgid.com
.amung.
x.translateth.
.scorecardresearch.
.newrelic.
.doctintuc.net
.infolinks.
.adroll.
.ants.vn
.doubleclick.
.google-analytics.
.vietad.vn
.4dsply.
.zercstas.
.k0z09okc.
.m2pub.
.baycdn.
.adnxs.
.solo.
.prizespolice.eu
.steepto.

#------------------------------------
# Catch-all exceptions
{-block}
/.*ad(sl|v(i[cs]|o|an|ertencia|ent|.*search|erse))
/.*(lo|thre|he|d|gr|l|ro|re|squ|class(ified)?)ads
/.*account
support./(.*/)?track
/.*\.git/objects/
/.*Bugtracker
/(.*/)?pop[a-z_-]*menu
.edu
.ac.*/
.uni-*.de
.tu-*.de
.gov
.hs-*.de
.fh-*.de
.org/.*(image|banner)
.dantri*.vcmedia.vn
.vietnamnet.vn/VideoJs/ads.js
api.adtimaserver.vn/zad/
.bing.com/rms/
.amazon.co.jp
.ebay.com/
adguard.com
.3kshop.vn
.facebook.com/.*aff*=
embed.vietnamnettv.vn/Scripts/videojs/
video.vietnamnet.vn/Scripts/videojs/
.shopee.vn/api/banner/batch_list
.cgv.vn/media/
.zadn.vn
.tikicdn.com/.*?ts/banner/
vnsharing.site/forum/vbbdesign/vnsharing/img/
openuserjs.org/scripts/
i.pximg.net/c/
.google.com/recaptcha/
*images.nutaku.com
.kissmanga.com
.messenger.com/ajax/presence/
.firstpartysimulator.net
.firstpartysimulator.org
panopticlick.eff.org
play.google.com
stat.s3blog.org
crvlck.com
csgostats.gg
.thanhnien.vn/v3/Jscripts/
.badssl.com
.jsdelivr.net/npm/
.90phut.click
.csgostats.gg

#----------------------------------------------------------------------------
# Catch-all for false-positives that are just TOO obvious to let go
{+block{Catch-all}}
.ads[erv][rv]*.
.ads.
/(.*/)?ad(se?rv|click|stream|image|log|farm|script)
/.*(top|bottom|left|right|text)_?ad

#------------------------------------
# Catch-all exceptions
{-block{Catch-all}}
/.*desktopadmin
/(.*/)?(player|radio|tv|television).?pop
/(.*/)?pop[-_]?(up|over|under|open(er)?)?s?(/|\.)(player|radio|tv|television)
/.*download
pgl.yoyo.org
.liquipedia.net/(.*/)load.php?

#----------------------------------------------------------------------------
# Misc Web-bugs, JS and just plain Junk. Images here aren't normal images.
{+block{web-bug} +handle-as-empty-document -handle-as-image}
/b/ss/.+
/HG\?hc=
.visistat.com
.google-analytics./
.overture.
.doubleclick.net/adi
.doubleclick.net/(.*/)?adj/
view.atdmt.com/(.*/)?iview/
tracking.
/(.*/)?adjs\.php\?
.bc.yahoo.com/b\?P=
x*.alexa.com
/event.ng/
/(eluminate|cm)\?[tc]i=\d+&st=\d+&
.snapfiles.net/rotation/.*\.asp
spa.snap.com/
.insitemetrics.com/
.extreme-dm.com/
stats.reinvigorate.net/
.getclicky.com/
.quantserve.com
media.adrevolver.com/
.chartbeat.com/(.*/)?chartbeat\.js$
js.adlink.net/
.sitestat.com/
pagead*.googlesyndication./.*\.js
scripts.chitika.net/.*\.js
.adinterax.com/.*\.js
.googleadservices.com/gampad/.*\.js
/.*/ad\.js\?
/.*omniture.*\.js
.gemius.pl/
farm.plista.com/widgetdata.php
.adnxs.com/
service.maxymiser.net/
.tynt.com/
pool.*.adhese.com/
/scripts/webtrends\.js
oskar.tradera.com/5
.adcash.com/script/
.ioam.de/
t.vi-serve.com/
pixel.inforsea.com/
#
/.+\.sitecatalyst\.js
/.+\.webtrekk\.js
/(.*/)?livehit=
/(.*/)?record&key=
/(.*/)?__utm\.gif
/(.*/)?a\.logrequest\.yolx\?
/(.*/)?aa\.php\?anuid=
/(.*/)?adam\.js
/(.*/)?add_page_view\?
/(.*/)?additional\.php\?res_width=\$script
/(.*/)?adlogger_tracker\.js\?
/(.*/)?adlogger_tracker\.php
/(.*/)?AdobeCustomVideoMeasurement\.swf
/(.*/)?adtracker\.
/(.*/)?aegis_tracking\.js
/(.*/)?afrpt\.gif\?
/(.*/)?aggbug\.aspx\?
/(.*/)?ajaxservice\.svc/registersession\?session_id=
/(.*/)?alllinksclicktracker\.js
/(.*/)?analysis-logger/logger\?
/(.*/)?analyzer/aa\.php\?
/(.*/)?aspstats/index\.asp\?
/(.*/)?astrack\.js
/(.*/)?astracker\.js
/(.*/)?atapixel\.js
/(.*/)?audiencescience\.js
/(.*/)?awstats\.js
/(.*/)?awstats_misc_tracker\.js
/(.*/)?b/ss/.*&ce=iso-8859-1&
/(.*/)?b/ss/.*&ce=utf-8&
/(.*/)?b/ss/.*&events=
/(.*/)?b/ss/.*&pagename=
/(.*/)?b/ss/.*/h\.17--wap\?c20=
/(.*/)?b/ss/.*=event36&
/(.*/)?b/ss/.*=referrers&
/(.*/)?b/ss/.*\?[aqb]&ndh=
/(.*/)?b/ss/.*\?aqb=1&ndh=
/(.*/)?b/ss/.*\?aqb=1&pccr=
/(.*/)?b/ss/.*\?gn=mobile:
/(.*/)?b/ss/.*\?pagename=
/(.*/)?b/ss/ueglobaldev/
/(.*/)?b/ss/wdgdolad,
/(.*/)?baynote-observer\.js
/(.*/)?baynote-search\.js
/(.*/)?baynote-single-local\.js
/(.*/)?baynote\.js
/(.*/)?baynote/
/(.*/)?baynoteobserver/
/(.*/)?beacon\?
/(.*/)?bh_counter\.js
/(.*/)?bluekai\.js
/(.*/)?bm-analytics-trk\.js
/(.*/)?bsuite/worker\.php\?
/(.*/)?cdn5\.js\?
/(.*/)?cdx\.gif\?
/(.*/)?cedexis\.js
/(.*/)?cedexis/
/(.*/)?certifica-js14\.js
/(.*/)?certifica\.js
/(.*/)?certifica_2010\.js
/(.*/)?cgi-sys/count\.cgi\?df=
/(.*/)?chartbeat\.js
/(.*/)?chcounter/
/(.*/)?clickheat\.js
/(.*/)?clickheat\^
/(.*/)?clickstream\.js
/(.*/)?cm\?ci=.*&tid=
/(.*/)?cm\?tid=
/(.*/)?cnstats/cntg\.php\?
/(.*/)?cnt-combined\.php\?
/(.*/)?com_astatspro/
/(.*/)?com_joomla-visites/
/(.*/)?com_joomlawatch/
/(.*/)?comscore\.js
/(.*/)?comscore_beacon\.js
/(.*/)?counter\.php\?chcounter_mode=
/(.*/)?counter/hit\.php\?referrer=
/(.*/)?countpixel\.
/(.*/)?criteo\.js
/(.*/)?csi\?v=.*&action=
/(.*/)?cxense/cx\.js
/(.*/)?cyberestat/
/(.*/)?dcs\.gif\?
/(.*/)?demandbase\.js
/(.*/)?dotomi_tracking/
/(.*/)?dtmtag\.js
/(.*/)?dwanalytics\.js
/(.*/)?e086ec\.aspx\?q=l3mkwgak
/(.*/)?e107_plugins/log/log\.php\?
/(.*/)?eae-logger/
/(.*/)?econa-site-search-ajax-log-referrer\.php
/(.*/)?econa-site-search/log\.php\?
/(.*/)?edata\.js
/(.*/)?elqcfg-\$script
/(.*/)?elqcfg\.js
/(.*/)?elqimg\.js
/(.*/)?elqnow/
/(.*/)?eluminate\?
/(.*/)?emos2\.js
/(.*/)?epf_v1_95\.js
/(.*/)?estatnativeflashtag\.swf
/(.*/)?event\.ng/
/(.*/)?exaonclick\.js
/(.*/)?finalizestats\.js
/(.*/)?fkounter/
/(.*/)?fkounter5/
/(.*/)?foresee/
/(.*/)?fpc\.pl\?a=
/(.*/)?fpcount\.exe
/(.*/)?fsrscripts/
/(.*/)?ga-custom-tracking\.
/(.*/)?ga-event-tracking\.
/(.*/)?ga-links\.js
/(.*/)?ga-multidomain\.
/(.*/)?ga-socialtracker\.
/(.*/)?ga-track\.
/(.*/)?ga-tracker\.
/(.*/)?ga-tracking/
/(.*/)?ga\.aspx\?utmac=\$image
/(.*/)?ga\.php\?name=\$image
/(.*/)?ga\.php\?utmac=\$image
/(.*/)?ga/trackevent\.
/(.*/)?ga_dualcode_tracking\.
/(.*/)?ga_event_tracking\.
/(.*/)?ga_header\.
/(.*/)?ga_keyword2\.
/(.*/)?ga_link_tracker_
/(.*/)?ga_loader\.
/(.*/)?ga_social_tracking\.js
/(.*/)?ga_social_tracking_
/(.*/)?ga_track\.php\?adurl=
/(.*/)?ga_tracker\.
/(.*/)?ga_tracklinks\.
/(.*/)?gaaddons-
/(.*/)?gaaddons\.js
/(.*/)?gaclicktracking\.
/(.*/)?gadsfuncs\.
/(.*/)?gallerystats\.
/(.*/)?ganalytics\.
/(.*/)?gapagetracker\.
/(.*/)?gapro-1\.swf
/(.*/)?gapro-1h\.swf
/(.*/)?gapro\.swf
/(.*/)?gascript\.
/(.*/)?gasocialtracking\.
/(.*/)?gatag\.js
/(.*/)?gatc\.js
/(.*/)?gatrack\.
/(.*/)?gatracking\.
/(.*/)?gatrackingcampaigns/
/(.*/)?gatrackthis\.
/(.*/)?gatrackwww\.
/(.*/)?gcount\.pl\?
/(.*/)?gemius\.js
/(.*/)?gemius/
/(.*/)?getsidpixeltag\?sid=
/(.*/)?globalpagetracking\.js
/(.*/)?google-analyticator/
/(.*/)?google-analytics-for-wordpress/
/(.*/)?google_analytics-bc\.swf
/(.*/)?googleanalytics-prod\.swf
/(.*/)?googleanalytics\.swf
/(.*/)?googleanalytics/ga\.php\?\$image
/(.*/)?googleanalyticsmanagement\.swf
/(.*/)?googleanalyticsplugin\.swf
/(.*/)?headupstats\.gif\?
/(.*/)?heatmap\.js
/(.*/)?heatmap_log\.js
/(.*/)?hg\?hc=&hb=.*&vjs=
/(.*/)?hgct\?hc=&hb=.*&vjs=
/(.*/)?hitcounter\.dll
/(.*/)?hoteltracking/pix\.gif\?
/(.*/)?hs_track\.js
/(.*/)?i\?siteid=
/(.*/)?images/spacer\.gif\?q=l3mkwgak
/(.*/)?imawebcookie\.js
/(.*/)?index\.php\?_m=livesupport.*&referrer=
/(.*/)?intervigil\.js
/(.*/)?iperceptions\.js
/(.*/)?ipixel\?spacedesc=
/(.*/)?iqtm\.js
/(.*/)?istat\.aspx\?
/(.*/)?ivwanalytics\.swf\?
/(.*/)?ivwbox/
/(.*/)?js/hbx\.js
/(.*/)?js/tagging/tagtrack\.js
/(.*/)?kaizentrack/
/(.*/)?kelkooid\?sitename=
/(.*/)?kissmetrics\.js
/(.*/)?kissmetrics/
/(.*/)?layer_log\.php\?p=
/(.*/)?leadgen_tracking\.js
/(.*/)?library/svy/.*/broker\.js
/(.*/)?library/svy/broker\.js
/(.*/)?linkinformer\.js
/(.*/)?livezilla/server\.php\?request=track&
/(.*/)?log\.php\?owa_timestamp=
/(.*/)?log_e\.php\?id=
/(.*/)?logaholictracker\.php\?
/(.*/)?logger/p\.gif\?
/(.*/)?logging/pixel\?
/(.*/)?md\.js\?country=
/(.*/)?mdwtc/click_thru/
/(.*/)?metriweb\.js
/(.*/)?metriweb/spring\.js
/(.*/)?mint/\?js
/(.*/)?mintstats/\?js
/(.*/)?mixpanel_beacon\.
/(.*/)?mmclient\.js
/(.*/)?mmcore\.js
/(.*/)?mngi/tracking/
/(.*/)?modules/contrib/google_analytics/
/(.*/)?modules/contributions/google_analytics/
/(.*/)?modules/google_analytics/
/(.*/)?modules/google_analytics_event_tracking/
/(.*/)?mpel/mpel\.js
/(.*/)?msftaudience\.js
/(.*/)?mtvi_reporting\.js
/(.*/)?mwtag\.js
/(.*/)?mwtag_flash\.js
/(.*/)?myasg/stats_js\.asp
/(.*/)?mycounter/counter_in\.php\?
/(.*/)?mystats/track\.js
/(.*/)?netmind-\$script
/(.*/)?netupdate/live\.php\?
/(.*/)?nielsen\.js
/(.*/)?nielsen/
/(.*/)?nielsenscv53\.\$script
/(.*/)?nielson_stats\.js
/(.*/)?njs\.gif\?
/(.*/)?nm_tr_combined-min\.js
/(.*/)?nm_tr_combined\.js
/(.*/)?nm_track\.js
/(.*/)?nm_trck\.gif\?
/(.*/)?ntpagetag\.aspx
/(.*/)?ntpagetag\.gif
/(.*/)?ntpagetag\.js
/(.*/)?ntrack\.asp\?
/(.*/)?oas_analytics\.js
/(.*/)?odoscope\.js
/(.*/)?omnitureanalytics\.swf\?
/(.*/)?onestat\.js
/(.*/)?opinionlab\.js
/(.*/)?owa\.tracker-combined-min\.js
/(.*/)?pagelogger/connector\.php\?
/(.*/)?pbstrackingplugin\.swf
/(.*/)?php-stats\.js
/(.*/)?php-stats\.php\?
/(.*/)?php-stats\.phpjs\.php\?
/(.*/)?php-stats\.recjs\.php\?
/(.*/)?phpmyvisites\.js
/(.*/)?piwik\.js
/(.*/)?piwik\.php
/(.*/)?pixelstats/
/(.*/)?planetstat\.php\?
/(.*/)?plugins/google-analytics/
/(.*/)?pphlogger\.js
/(.*/)?pphlogger\.php
/(.*/)?pr\.php\?
/(.*/)?prnx_track\.js
/(.*/)?quant\.js
/(.*/)?quantcast\.js
/(.*/)?rbi_us\.js
/(.*/)?rbipt\.gif\?
/(.*/)?rbipt\.js
/(.*/)?rcdntpagetag\.js
/(.*/)?redirectexittrack\.php\?
/(.*/)?remote/js_logger\.php
/(.*/)?revenuescience\.js
/(.*/)?revsci\.js
/(.*/)?s\.gif\?l=
/(.*/)?savetracking\?
/(.*/)?scripts/hbx\.js
/(.*/)?sdc_tag\.js
/(.*/)?sdctag\.js\?
/(.*/)?sdxp1/dru4/meta\?_hc=
/(.*/)?server\.php\?request=track&output=
/(.*/)?shinystat\.cgi\?
/(.*/)?shopify_stats\.js
/(.*/)?simple-google-analytics/
/(.*/)?simtracker\.min\.js
/(.*/)?sitestat\.js
/(.*/)?sitestats\.gif\?
/(.*/)?sitetrek\.js
/(.*/)?slimstat/
/(.*/)?softpage/stats_registerhit\.asp\?
/(.*/)?sophus/logging\.js
/(.*/)?sophus3/logging-code\.js
/(.*/)?sophus3/logging\.js
/(.*/)?sophus3_logging\.js
/(.*/)?staffcp/save_stats\.php\?
/(.*/)?stat/track\.php\?mode=js
/(.*/)?stat36/stat/track\.php
/(.*/)?stataffs/track\.php\?
/(.*/)?statcounter\.js
/(.*/)?statcountex/count\.asp\?
/(.*/)?stateye/
/(.*/)?stats/et_track\.asp\?
/(.*/)?stats/track\.asp\?
/(.*/)?stats/tracker\.gif\?
/(.*/)?statsadvance\.js
/(.*/)?statscript\.js
/(.*/)?statspixel\.php\?
/(.*/)?store-uniq-client-id\?bomuuid=
/(.*/)?stwc-counter/
/(.*/)?stwc/code\.js
/(.*/)?supertracking\.
/(.*/)?swfaddress\.js\?tracker=
/(.*/)?szm_mclient\.js
/(.*/)?tacoda_ams_ddc_header\.js
/(.*/)?tagomnitureengine\.js
/(.*/)?tc_logging\.js
/(.*/)?tc_targeting\.html
/(.*/)?tc_throttle\.js
/(.*/)?tnsmetrix/
/(.*/)?touchclarity/
/(.*/)?tpix\.gif\?
/(.*/)?track/.*\?rnd=0\.\$image
/(.*/)?tracker/event\?
/(.*/)?tracking/beacon/\?
/(.*/)?tracking/tag_commander\.php\?
/(.*/)?tracking/tynt_
/(.*/)?trackingpixels/get\?referrer=
/(.*/)?traffic/status\.gif\?
/(.*/)?traffic4u\.js
/(.*/)?udctrack\.
/(.*/)?uim\.html/
/(.*/)?unique/track\.gif\?
/(.*/)?userfly\.js
/(.*/)?vanillastats/js/track\.
/(.*/)?view_stats\.js\.php
/(.*/)?viperbar/stats\.php\?
/(.*/)?visitortracker\.pl\?
/(.*/)?visualsciences\.js
/(.*/)?visualstat/stat\.php
/(.*/)?vs_track\.gif\?
/(.*/)?vstat\.php
/(.*/)?vstats/counter\.php
/(.*/)?vtrack\.php\?
/(.*/)?webabacus-\$script
/(.*/)?webforensics/
/(.*/)?webiq\.js
/(.*/)?WebStatistik/.*\.pl\?
/(.*/)?webstatistik/track\.asp
/(.*/)?webtraxs\.js
/(.*/)?webtrekk\.js
/(.*/)?webtrekk\^
/(.*/)?webtrekk_
/(.*/)?where-go-add\.js\.php\?
/(.*/)?who/\?js
/(.*/)?whoson_.*_trackingonly\.js
/(.*/)?wlexpert_tracker\.
/(.*/)?wlexpert_tracker/
/(.*/)?wp-clickmap/
/(.*/)?wp-content/plugins/stats/count\.php\?
/(.*/)?wp-counter\.php
/(.*/)?wp-js/analytics\.js\?
/(.*/)?wp-powerstat/
/(.*/)?wp-slimstat/
/(.*/)?wt_capi\.js
/(.*/)?wtbase\.js
/(.*/)?wtcore\.js
/(.*/)?wtid\.js
/(.*/)?wtinit\.js
/(.*/)?wusage_screen_properties\.gif\?
/(.*/)?wysistat\.js
/(.*/)?xgemius\.js
/(.*/)?xiti\.js
/(.*/)?xmint/\?js
/(.*/)?xtclicks-\$script
/(.*/)?xtclicks\.js
/(.*/)?xtclicks_
/(.*/)?xtcore\.js
/(.*/)?xtcore_
/(.*/)?xtrack\.php\?
/(.*/)?xtroi\.js
/(.*/)?yalst/pixel.*\.php\?
/(.*/)?zag\.gif\?
/(.*/)?~utm_gif\?
/.*-publicite\.
.be/ads\.
.be/ads/
.ch/ads\.
.ch/ads/
.fr/ads\.
.fr/ads/
/(.*/)?acurax-on-click-pop-under/
/(.*/)?ad728x90\.
/(.*/)?ads_server_
/(.*/)?adserverpub\?
/(.*/)?bandeaupublicite/
/(.*/)?call/pubj/
/(.*/)?pub300-250\.
/(.*/)?pub728-90\.
/(.*/)?publicite-
/(.*/)?publicite\.
/(.*/)?publicite/
/(.*/)?publicite_
/(.*/)?publicites\.
/(.*/)?publicites/
/(.*/)?regie_pub/
/(.*/)?regiepub/
/(.*/)?toolbarxooit/toolbar.*\.js
/(.*/)?wp-content/plugins/no-adblock/
/.*_publicite\.
/.*_publicite1\.
/.*_publicite_
/.*_regiepub/

{+block{web-bug} -handle-as-empty-document +handle-as-image}
/(.*/)?__utm.gif\?
/.*\.gif\?D=DM
stats./c?rc/.*/uc.gif
/(.*/)?dcs.gif\?&?dcs
/(.*/)?c(lear)?\.gif\?.
/(.*/)?(clear|blank|(trans_?|1x)?1).gif\?.
stats./.*\.gif\?
.yieldmanager.com/pixel\?
.analytics.yahoo.com
go.idmnet.bbelements.com/please/showit/
gm-link.com/
collector.githubapp.com/
.consensu.org/delivery/pixel\.php
.pixel.parsely.com/
t.9gag.com/img\.gif
.connectaserver.de/
/(.*/)?RealMedia/ads/
/(.*/)?adserver\.php

{+block{Generic-Site-specific}}
.sedoparking.com/
landing.trafficz.com/
.searchnut.com/\?domain
wwwz.websearch.verizon.net/search\?qo=
.hitbox.com
.the-gadgeteer.com/cgi-bin/getimage.cgi/
dest.travelocity.com/website/destinations/images/partner_frommers.gif
dest.travelocity.com/website/destinations/images/travelex_logo.gif
i.imdb.com/Photos/CMSIcons/(?!buttons|emoticons)
rcm.amazon.com
.nytimes.com/adx/
.adtrak.net
.elitemediagroup.net
.popuptraffic.com
.hit-now.com
[a-v]*.valueclick.com
.cpays.com
.oxado.com
.adult*finder.com
/scripts/cms/xcms.asp
/.*intellitxt/
.intellitxt.com
.kontera.com
.tribalfusion.com/ctxt
.klipmart.com
ad*.com.com
sales.liveperson.net
.iad.liveperson.net
.coremetrics.com/
.realmedia.com/data/
.revsci.net
.clickability.com
/.*clickability(.com)?/
stats.*.ihost.com
.2o7.net
.webtrends.com
.tacoda.
ad.theadhost.com
.adbureau.net
.adgardener.com
.revenue.net
.geocities.com/js_source
.dartsearch.net
.zedo.com
.trk.sodoit.com/
.espace.netavenir.com
.hitfarm.com
.topnemo.com/engine
.top100categories.com/engine
/(t|search)\.php\?uid=ws[a-z0-9]+\.[a-z0-9]+
.adinterax.com/(?!(.*)\.(js|gif|jpg))
img.bluehost.com
linuxinsider.com/images/sda/
[a-z].clickdensity.com
.widgetbucks.com
img.dailymail.co.uk/i/promo_boxes/
.fimserve.com
static.lycos-europe.net
82.99.18.195
.atdmt.com/
.awin1.com
.adjuggler.com/servlet/ajrotator/
bcc.co.uk/
fusion.adtoma.com/
.chartbeat.net/(.*/)?ping\?
.atemda.com/
.omtrdc.net/
www91.intel.com/
reklamy.sfd.pl/
rotation.linuxnewmedia.com/
de17a.com/
cltomedia.info/delivery/
.adexprt.com/
data.gosquared.com/
resources.infolinks.com/
abs.proxistore.com/abe/
rtax.criteo.com/
static.criteo.net/
static.criteo.com/
static.*.criteo.net/
cas.*.criteo.com/
cas.criteo.com/
/js\.ng/
/popunder
/t\.php\?cat=.*&kw=.*&sc=
jlinks.industrybrains.com/
js.adsonar.
bwp.
.yahoo.com/mc/stampNonJs

{+block{Restrained Access}}
# Google
/(.*(/|%2F))?doubleclick\.net(/|$|%2F|:)
/.*=https?(://|%3A%2F%2F)googlead(api)(\.|/)?s\.
/(.*(/|%2F))?google(-analytics|adservices|commerce|syndication|tag(manager|services))\.com(/|$|%2F|:)
/.*=https?(://|%3A%2F%2F)(www-)?google-analytics\.
/(.*(/|%2F))?cse\.google\.com(/|$|%2F|:)
/.*=https?(://|%3A%2F%2F)www\.google\.com/(cse|friendconnect)/
/.*=https?://(cse|www)\.google\.(com|fr)/coop/cse/brand\?
/(.*/)?trustedstores/
/.*=https?(://|%3A%2F%2F)clients?[0-9]+\.google\.(com|fr)/
/(.*/)?gen(erate)?_204($|\?)
.metric.gstatic.com
.accounts.google.com/o/oauth2/postmessageRelay\?
.ssl.gstatic.com/accounts/o/[0-9]+-postmessagerelay\.js$
.youtube-nocookie.com/
# Suggestions
#.bing.com/AS/Suggestions\?
#/(.*/)?complete/search\?sclient=psy-ab&
# Domaines
/(.*(/|%2F))?247realmedia\.com(/|$|%2F|:)
/(.*(/|%2F))?amung\.us(/|$|%2F|:)
/(.*(/|%2F))?(a2dfp|adhoc[0-9]+|adlure)\.net(/|$|%2F|:)
/(.*(/|%2F))?(adap|admo)\.tv(/|$|%2F|:)
/(.*(/|%2F))?(abtasty|acces-vod|affiliation-france|alibaba|angsrvr|antvoice|atdmt|atinternet|audiencesquare|aweber|acxiom-online|authorisationimprint)\.com(/|$|%2F|:)
/(.*(/|%2F))?(ad2perf|addthis|adikteev|adleadevent|adlooxtracking|adlpartner|adnetworkperformance|adnxs|adroll|adsafeprotected|adsclean|adslvr|adsrvr|adtechus|advertising|adxpansion|amazon-adsystem)\.com(/|$|%2F|:)
/(.*(/|%2F))?(afilias-nst)\.(info|org)(/|$|%2F|:)
/(.*(/|%2F))?adsrvr\.org(/|$|%2F|:)
/(.*(/|%2F))?audienceinsights\.net(/|$|%2F|:)
/(.*(/|%2F))?basilic\.io(/|$|%2F|:)
/(.*(/|%2F))?beap-bc\.yahoo\.com(/|$|%2F|:)
/(.*(/|%2F))?(bazaarvoice|bidtrk|bluekai|brightcove|buysellads|byvue)\.com(/|$|%2F|:)
/(.*(/|%2F))?bidswitch\.net(/|$|%2F|:)
/(.*(/|%2F))?(clicks4ads|commander[0-9]+|truste|cupinteractive|customtrickers|cxense)\.com(/|$|%2F|:)
/(.*(/|%2F))?(chartbeat|clickintext)\.net(/|$|%2F|:)
/(.*(/|%2F))?(de17a|desktopadx|disqus(cdn)?|doofinder|dotomi)\.com(/|$|%2F|:)
/(.*(/|%2F))?(demdext|digimondo)\.net(/|$|%2F|:)
/(.*(/|%2F))?(email(-match|retargeting)|emjcd|esprit-click|estat|europacash|exoclick)\.com(/|$|%2F|:)
/(.*(/|%2F))?(easydmp)\.net(/|$|%2F|:)
/(.*(/|%2F))?fi_user\.js(/|$|%2F|:)
/(.*(/|%2F))?formr\.io(/|$|%2F|:)
/(.*(/|%2F))?(ftv-publicite|fullscreens)\.fr(/|$|%2F|:)
/(.*(/|%2F))?(famust|fia-net|ftjcfx)\.com(/|$|%2F|:)
/(.*(/|%2F))?(fastly|fwmrm)\.net(/|$|%2F|:)
/(.*(/|%2F))?(gigya|gravityrd-services|gwallet)\.com(/|$|%2F|:)
/(.*(/|%2F))?(h6e)\.net(/|$|%2F|:)
/(.*(/|%2F))?(hotjar|howtank)\.com(/|$|%2F|:)
/(.*(/|%2F))?gemius\.pl(/|$|%2F|:)
/(.*(/|%2F))?(iadvize|imrworldwide|infolinks)\.com(/|$|%2F|:)
/(.*(/|%2F))?ip-label\.net(/|$|%2F|:)
/(.*(/|%2F))?jublo\.net(/|$|%2F|:)
/(.*(/|%2F))?(kameleoon|kissmetrics)\.com(/|$|%2F|:)
/(.*(/|%2F))?(leadin|leguide|lengow|ligatus|liveintercept|liverail)\.com(/|$|%2F|:)
/(.*(/|%2F))?livecount\.fr(/|$|%2F|:)
/(.*(/|%2F))?(mediametrie|sdv|weborama)\.fr(/|$|%2F|:)
/(.*(/|%2F))?(1x12|adform|digiteka|edgecastcdn|elasticad|emsecure|ezakus|hs-analytics|krxd|nocookie|nuggad|openx|sexypartners?|trafficjunky|typekit|web-boosting|yceml)\.net(/|$|%2F|:)
/(.*(/|%2F))?mc\.yandex\.ru(/|$|%2F|:)
/(.*(/|%2F))?(media-clic|mediabong|mediapeo[0-9]*|medleyads|mgid|mindlytix|ml[0-9]+|mmtro|mobiopush|mprezchc|mysafeurl)\.com(/|$|%2F|:)
/(.*(/|%2F))?(adtech|meetrics)\.de(/|$|%2F|:)
/(.*(/|%2F))?(natoms|navilytics|newrelic|nxtck)\.com(/|$|%2F|:)
/(.*(/|%2F))?(non)\.li(/|$|%2F|:)
/(.*(/|%2F))?(oclaserver|okoads|omnitagjs|onedmp|optimizely|optnmnstr|outbrain)\.com(/|$|%2F|:)
/(.*(/|%2F))?(orangeads|ownpage)\.fr(/|$|%2F|:)
/(.*(/|%2F))?onclickads\.net(/|$|%2F|:)
/(.*(/|%2F))?po\.st(/|$|%2F|:)
/(.*(/|%2F))?pxlad\.io(/|$|%2F|:)
/(.*(/|%2F))?(popads|popcash)\.net(/|$|%2F|:)
/(.*(/|%2F))?promotools\.biz(/|$|%2F|:)
/(.*(/|%2F))?(parsely|petametrics|popmyads|printfriendly|proxistore|prscripts|psma02|pubdirecte|publitek|pubmatic|pubmine|pureadexchange)\.com(/|$|%2F|:)
/(.*(/|%2F))?(quantserve)\.com(/|$|%2F|:)
/(.*(/|%2F))?(purl)\.fr(/|$|%2F|:)
/(.*(/|%2F))?(radkfifty|r66net|readspeaker)\.com(/|$|%2F|:)
/(.*(/|%2F))?(cedexis(-(radar|test))?|criteo|paigefair|revsci|rubiconproject|storetail)\.(com|net)(/|$|%2F|:)
/(.*(/|%2F))?(sascdn|scorecardresearch|sddan|semiocast|servebom|servedbyopenx|serving-sys|shareaholic|shopping|sitemeter|sitestat|skimresources|smartadserver|statcounter|steepto|stickyadstv|sumome)\.com(/|$|%2F|:)
/(.*(/|%2F))?seedingup\.fr(/|$|%2F|:)
/(.*(/|%2F))?share\.yandex\.ru(/|$|%2F|:)
/(.*(/|%2F))?silkenthreadiness\.info(/|$|%2F|:)
/(.*(/|%2F))?(taboola|tagcommander|themoneytizer|toroadvertisingmedia|torrents?-time|trafficstars?|traffichaus|trw[0-9]+|twitcount)\.com(/|$|%2F|:)
/(.*(/|%2F))?teads\.tv(/|$|%2F|:)
/(.*(/|%2F))?(taucdn|theremailer)\.net(/|$|%2F|:)
/(.*(/|%2F))?tpvl\.co(/|$|%2F|:)
/(.*(/|%2F))?tradelab\.fr(/|$|%2F|:)
/(.*(/|%2F))?(acamar|ttconfig)\.xyz(/|$|%2F|:)
/(.*(/|%2F))?trafficfactory\.biz(/|$|%2F|:)
/(.*(/|%2F))?trust\.zone(/|$|%2F|:)
/(.*(/|%2F))?(usersnap|uservoice)\.com(/|$|%2F|:)
/(.*(/|%2F))?(venturead|videoadex|videostep|vigilink|vintercative|visualrevenue)\.com(/|$|%2F|:)
/(.*(/|%2F))?(webtrends||wwwpromoter|wysistat|wonderpush)\.com(/|$|%2F|:)
/(.*(/|%2F))?windows\.net(/|$|%2F|:)
/(.*(/|%2F))?xiti\.com(/|$|%2F|:)
/(.*(/|%2F))?yadro\.ru(/|$|%2F|:)
/(.*(/|%2F))?y-track\.com(/|$|%2F|:)
/.*=https?(://|%3A%2F%2F)([a-z]+\.)?telemetry(\.|-)
# URL
/.*=https?(://|%3A%2F%2F)ad(4|s)?(by|serve)?(\.|-)
/.*=https?(://|%3A%2F%2F)(ad2play|adprovider|adtrack|adyoulike|affiliate)\.
/.*=https?(://|%3A%2F%2F)beacon\.
/.*=https?(://|%3A%2F%2F)(cdn-analytics|cli?ck(cdn)?|consent|counter|counts?)\.
/.*=https?(://|%3A%2F%2F)(a-cedexis|cedexisprivate|cedexispub)\.
/.*=https?(://|%3A%2F%2F)bouncer\.
/.*=https?(://|%3A%2F%2F)consumer-metrics?-
/.*=https?(://|%3A%2F%2F)(delivery|detection)\.
/.*=https?(://|%3A%2F%2F)ea\.
/.*=https?(://|%3A%2F%2F)((anvil|delivery|2?waycm)-)?geo(\.|-)
/.*=https?(://|%3A%2F%2F)gscounters?\.
/.*=https?(://|%3A%2F%2F)openx\.
/.*=https?(://|%3A%2F%2F)pagead\d?(\.|-)
/.*=https?(://|%3A%2F%2F)(partners?ads?)\.
/.*=https?(://|%3A%2F%2F)(regie(trk)?|rotator)\.
/.*=https?(://|%3A%2F%2F)(ping|pix[0-9]+|pixel|piwik|publicite|pubs?)\.
/.*=https?(://|%3A%2F%2F)(securepubads|serve-adserver|syndication)\.
/.*=https?(://|%3A%2F%2F)soads\.
/.*=https?(://|%3A%2F%2F)stats?\.
/.*=https?(://|%3A%2F%2F)(tags?|tracker4?|track(ing)?|trk)\.
/(.*(/|%2F))?(ablckd|ad(images|request)?|ads|adsense|behavior|campaigns?|cdx-radar|home-menu-ads|measurement|metrika|metter|pagead|pixel|platformtelemetry|textad|track(imp)?|UploadAds|videoads|vtttrack)(/|%2F)
/(.*(/|%2F))?(ads?|adsolution|controltag|count(er)?|hit|(hit\.)?xiti|noauthtracker|ping|pixel|stats?|(rum-)?track(ing)?)(\?|$|;)
/((.*(/|%2F))?|.*_)(ads?|adServer|adstream|adtechv[0-9]+|analytics|count(er)?|nugg|smartad|request_tracker|tagcommander|xtcore|xtroi|ytrack)(_|\+|\.)
/(.*(/|%2F))?ptrack-
# JavaScript
/(.*(/|%2F))?(a2d_displayAds|adblock|ads?frame|ads?|ads-ext|adsbygoogle|adsense|adserve|advertisement|advertising(banner)|adx|analytics|beacon|chartbeat(_mab)?|cookieconsents?|doubletrack|evercookie|foglio|ga|geoloc|googlads|gpt|measure|nwGeoAds|outbrain|ping|piwik|publicite|px|radar|shareaolic|stats?|showads|track(js)?|vglnk|vrs|xtcore(\.prod|SimpleTag)?|xtclicks?|xtcoreETxtclicks|xtjwrm_[0-9]+)(\.min)?\.js(\?|$)
/.*(-|_|\.)(ads|adsense|analytics|gapro|trackers?)\.js(\?|$)
# Images
/(.*(/|%2F))?textlink-ads?\.jpg(\?|$)
/(.*(/|%2F))?(_|__(activity|ptq)|1x1|advert|beacon|botd|empty|p|ping|spacer|trpx)\.gif(\?|$)
/(.*(/|%2F))?(adblock|adchoice(_1)?|adVidoe|pix-all)\.png(\?|$)
# Script PHP
/(.*(/|%2F))?(adblocks?|ad[sx]?|count|basilic|cookies?|digiteka|displayad|etag|evercookie_(cache|etag)|hit|ping|j?stats?|track|viewCounter)\.php(\?|$)
# Script HTML
/(.*(/|%2F))?(cookies?|ip|stats?)\.html\?
# Script SWF
/(.*(/|%2F))?(evercookie)\.swf$
# Cookies
/(.*(/|%2F))?cookiechoices?\.js(\?|$)
/(.*(/|%2F))?cookie_policy\+
# Param tres
/.*(&|\?)(adsafe|affiliate_id|pub(id)?|publisherKey|streamingstats|tracker[0-9]+)=
/.*=(adgroups?|advget)
# Anti-bloqueurs
/(.*(/|%2F))?nm\.js(\?|$)
/(.*[^a-z])?campaign(_|/)
/(.*[^a-z])?fingerprint(=|\.)
/log/web?

{+block{Len}}
#TAG:^MAXIMUM-URL-LENGTH
TAG:^MAXIMUM-DOMAIN-LENGTH

{+block{Size}}
#TAG:^4\d$

#-------------------
# -
{-block}
/.*(watch|weather(/[0-9]+)?|\.(css|html|js)(\?[a-z0-9]+|\.gzip)?)\?[a-z]{1,}[0-9]?=
.fbcdn.net/.*?\.(jpe?g|gif|png)
.facebook.com/ajax/photos/snowlift/
[0-9]-edge-chat.facebook.com/ping?
.facebook.com/feed/options_menu/\?button_id?
americanpomade.vn
.config.skype.com
.fado.vn
.hltv.org/stats
tinhte.vn/appforo/
tinhte.vn/css.php?
.hdvietnam.com/hd-shops/
.napas.com.vn
.youtube.com/live_chat.*
hydrogenaud.io
znews-photo-td.zadn.vn
.facebook.com/ajax/haste-response/
/.*_blocking_ads_
/.*_ad_blocking_
iamcdn.net/players/ads.watch.js
hatde.tv/embed/tracking?
hatde.tv/embed/hydrax/
imgur.com/a/.*/embed?
anime47.com/ads/player/v/
.reddit.com/r/(.*[^a-z])?campaign(_|/)
gamepress.gg/arknights/sites/arknights/files/styles/
.fandom.com/wiki/(.*[^a-z])?Campaign(_|/)
liquipedia.net/commons/images/a/
tvhai.org/embed/ads_code_*
.voz.vn/css.php?
.twitter.com/i/api/
accounts.spotify.com
.csstats.gg
.reddit.com/r/

#----------------------------------------------------------------------------
# Site-specific block patterns;

{+block{WidgetsRules}}
widgets.digg.com/button
platform.linkedin.com/
.stumbleupon.com/badge/embed/
platform.tumblr.com/
/.*?tweet_button
w.sharethis.com
/.*?share.js
/.*?ga.js
/.*?widgets.js
/.*?analytics.js
/.*?addthis
/.*?plusone


#----------------------------------------------------------------------------
# Generic block-as-image patterns:
{+block-as-image}
/.*ad_?image\.(php|cgi)
/.*recips?/
/bandeaux/
/.*client_?ad\.(php|cgi)
/.*AIM_UAC.adp
/(.*/)?adserver/image
/(.*/)?ads/images/
/.*\?ad_(type|size)=
?r.atwola.com
.[a-vx-z]*.doubleclick.net/(?!(.*/)?ad[ji])
.*servedby.advertising.com
.yimg.com/.*\.yimg\.com/a/
.yimg.com/.*/flash/promotions/.*\.(gif|jpg)$
bs*.gsanet.com
bs*.einets.com
.qkimg.net
[abd-ux-z]*.atdmt.com/
.fastclick.net
.casalemedia.com
kermit.macnn.com/
quinst.com/images
valuepage.com/images
ia.imdb.com/.*\.swf
.reactivpub.
.as*.falkag.
a.tribalfusion.com/
.adserver.com/
.ru4.com/
.smartadserver.com/
admedia.
jmcms.cydoor.com/
.adtrix.com
*[0-9].tribalfusion.com/
.img*.mediaplex.com
a*farm.mediaplex.com/ad/fm/
matrix.mediavantage.
.cibleclick.com
.netracker.net
.interclick.com
.maxserving.com
.gonamic.de
.webads.
.adlegend.com
.belnk.com
.euros4click.
ads-*.quarterserver.
searchportal.information.com/
images.ibsys.com/
.lduhtrp.net/image
scripts.chitika.net/.*\.(gif|png|jpg)
.projectwonderful.com/gen.php
.akamai.net/.*\.adtech\.de/.*\.(gif|png)
.adinterax.com/.*\.(gif|jpg)
img.directtrack.com
.emediate.eu/
.googleadservices.com/~
.richmedia.yahoo.com/.*\.(gif|jpe?g)\?ad
.served.by.adshuffle.com/
.adsonar.com/.*/imgs/
.pclick.yahoo.com/images/
rover.ebay./ar.*\&adtype=
/tradedoubler/.*\.swf
hstse.tradedoubler.com/.*\.swf
www.zdnetasia.com/.*/sponsor/.*\.gif$
.googlesyndication.com/.*/imgad\?
optimize.indieclick.com/
optimized-by.rubiconproject.com/
g.adspeed.net/
imp.double.net/
.*.*.spylog.com/
statse.webtrendslive.com
spinbox.versiontracker.com/.*\.(gif|jpg)
stat.onestat.com
imp*.tradedoubler.com
stat.webmedia.
log*.xiti.com/
log*.hit-parade.com/
www.xml.eshop.msn.com/tracksponsorimpression.asp
.imrworldwide.com
.clicktracks.com
.etracker.
.x-traceur.com
content.ipro.com
.247realmedia.com
.searchignite.com
.statcounter.com
.research-int.se/data
.cybermonitor.com
log.go.com/log
stats.indextools.com
tra*.measuremap.com
.eurekster.com/sidebar
tra*.mybloglog.com
.guesttrace.
insightxe./data/
.insightfirst.com
rss.slashdot.org/~a/Slashdot/slashdot\?
rss.slashdot.org/~r/Slashdot/slashdot/~4/
[a-z][0-9].nedstatbasic.net/
feeds.feedburner.com/~r/.*/~4/
feedproxy.google.com/~r/.*/~4/
feeds.feedburner.com/~a/DilbertDailyStrip\?
track.webtrekk.de/
b.scorecardresearch.com/
sb.scorecardresearch.com/
b.collective-media.net/
.ivwbox.de/
s*.sitemeter.com/(meter|js/counter.js)
fastcounter.bcentral.com/
bilbo.counted.com/
.travelocity./Sponsor_gifs/
.weather.com/creatives/
.weather.com/web/services/email/
/.*/topslots/topslot
.contextweb.com/
.offermatica.com/
.adbrite.com
.jpost.com/images/\d+/promos/
.infoempleo.com/(pop-up|images(/Nueva/|/motor))
hera.hardocp.com/
leadback.advertising.
.yieldmanager.com/
.displayadsmedia.com
astalavista.box.sk/adult.*\.jpg
smartad.*.*.*
.dinside.no/annonsorer/
/RealMedia/ads/
/RealMediaAds/
/top\.php\?d=.*\.[a-z]{2,5}
.google.com/afsonline

#-------------------
# -
{-block}
TAG:.*?PRIVOXY-FORCE
/PRIVOXY-FORCE/
adsl.
ad[udmw]*.
adbl*.
adam*.
adapt*.
adob*.
adrenaline.
adtp*.
adv[oia]*.
adventure*.
.*road*.
.olympiad*.
.*load*.
.*[epu]ad*.
county*.
countr*.
metrics.torproject.org/
linuxcounter.net/
adina*.
adele*.
.faqs.org/banner\.html
bannerblind.mozdev.org
advogato.org
ad*.vhb.de
.globalintersec.com/adv
banners.wunderground.com/
.openoffice.org/banners/
.amazon.com/.*/banners/
.washingtonpost.com/wp-srv/
.gnome.org
.nycsubway.org/img/banner
.forgotten-ny.com/ADS/
counter.li.org
adrian.adrian.org
adela.karlin.mff.cuni.cz
.swcp.com/rtoads/
.privoxy.org
sourceforge.net/.*tracker
.brawnylads.com
adzapper.
.altavista.com/web/adv
rads.mcafee.com/
linuxfromscratch.org/
dv411.com/.*advc50
.freeswan.org/
www.arm.com/.*ads
www.anybrowser.org/
www.tads.org/
.mbe.com/redir/packtrack.asp
.iship.com/trackit/
.esis.com.au/AdvSerialCards
.familysearch.org/.*banner
coder.com/creations/banner/
arnolds.dhs.org/static/adv_tools.html
.gpl.org/
.europa.eu.
.schooner.com/~loverso/no-ads/
source.bungie.org/
adonthell.linuxgames.com/
.bbc.co.uk/
adc.netlabs.org/
.tela.bc.ca/tads/
adbusters.org/
.eads.*/
.qualcomm.com/brew/en/developer/resources/ad/
/update\d\d/.*adsnt.*
.microsoft.com/.*masthead
.indymedia.org
.seanbaby.com
.cels.org/.*track
/(.*/)?somerights20.gif
.creativecommons.org
.ups.com/.*/track
.adju.
.rubberslug.com
.freebsd.org
.fsf.org
.gnu.org
adium*.*.
.googleadservices./pagead/adclick
.garaget.org/annonser/
edge.macworld.com
.discovery./.*/topads/
.dawn.com/.*/(9690dina|aurora_award)\.
.google.com/reader/
.parcel2go.com/track
.amazon.com/gp/gift-central/.*recip/
.yimg.com/.*/themes/ad/
.ad.*/pub/mozilla.org/
lads.myspace.com
.shockwave.com/servlet/DownloadEcommTracker
.fish4.co.uk/.*ad
.mp3.com.au/.*popup
/(.*/)?dynamiskt/reklam_media/did_
switch.atdmt.com/action/
.parcelforce.com/.*track
.microsoft.com/.*/adschema/
.wikimedia.org/
.wikipedia.org/
.wiktionary.org/
.haxx.se/docs/adv_
www.google.com/adsense/
.encyclopediadramatica.com/
tags.gawker.com/.*css$
.tnt.co.uk/TrackNTrace/
/ups/track\.php
ad.doubleclick.net/crossdomain\.xml
.doubleclick.net/.*/DartShell.*\.swf
.doubleclick.net/.*/DARTSHELLCONFIGXML
real.custhelp.com/cgi-bin/real\.cfg/php/enduser/popup_adp\.php
fritz.fonwlan.box/
fritz.box/
.adobe.com
qa.debian.org/popcon
.mta.info/.*advmain.htm$
.proaurum.de/banner[ABC]\d_?/
.goldmoney.com/
.ad.nl/
.yimg.com/.*/ads/bestofygroups.jpg$
.nytimes.com/.*/ads\.css$
.turner.com/cnn/.*/AdServiceAdapter.swf
lads.myspacecdn.com/
.phobos.apple.com/
.emediate.eu/.*EASLink=
.meteo.pl/advajax\.js
adressa.no/
adresseavisen.no/
.facebook.com/.*/track.php
.tads.org/
adtoma.com/
adactio.com/
www.peereboom.us/adsuck/
.svd.se/.*\.css($|\?)
include.ebaystatic.com/.*omniture.*\.js
.yimg.com/d/combo\?
/.*\.css$
adesklets.sourceforge.net/
adassier.wordpress.com/
adassier.files.wordpress.com
adainitiative.org/
adjamblog.wordpress.com/
adjamblog.files.wordpress.com/
.urbandictionary.com/popular
websupport.wdc.com/
.conrad.se/newsletter/
.wlxrs.com/
.advrider.com/
/.*ADVrider
adn.speedtest.net
.bundestag.de/
.rote-hilfe.de/
.stackexchange.com/(.*/)?popup
.stackoverflow.com/(.*/)?popup
.serverfault.com/(.*/)?popup
.superuser.com/(.*/)?popup
.stopwatchingus.info/
.amnesty.de/
.mirrorcreator.com
.thuonggiado.
.aeriastatic.com
.photobucket.com
.sourceforge.net
regex101.com
.hosting.vcmedia.vn
.answcdn.
vnsharing.net/forum/images/img/
.deviantart.
.mangahead.
.windowsupdate.com
.*download.
.download*.
.*downloads.
.mangaupdates.com/images/
.avishop.vn
.sap.com/.*banner
.pfs.vn
.head-fi.org
.animemusicvideos.org
.apple.com
.sonymusic.
.mixi.
.google.com/uds/api/
.google.com/.*q=
/upload/
/uploads/
.gstatic.
/wp-content
/get_video_info
.mega.co.nz
.ytimg.
.mp3.zdn.vn
movies.hdviet.
.anichart.net
.github.io
.tpb.vn
mail.google.com
accounts.google.com
translate.google.com
upload.wikimedia.org
.hayhaytv.vn/vod
.githubusercontent.com
.lazada.
.blueserving.
.adtimaserver.vn
/.*?crossdomain\.xml
.vcmedia.vn/js/mingid_core.js
.blogspot.com/.*?adx.*?png
.blogspot.com/.*?adx.*?jpg
.counter-strike.net
img-s-msn-com.akamaized.net
.appex-rf.msn.com
.wikia.com
.nocookie.net
csgo-stats.com
vcdn.tikicdn.com
.facebook.com/ajax/pagelet/
.youtube.com/api/timedtext?
wmedia.adk2x.com
.githubusercontent.com/kjllmeplz/.*?\.(gif|GIF|jpg|js)$
static.xx.fbcdn.net/rsrc.php/.*?\.(css|js)$
.google.com.vn/xjs/
.google.com/xjs/
apis.google.com
.comicvn.net/.*?readmanga.js?
.sndcdn.com/media/
.accesstrade.vn
.insight.fis.vn
.uniad.
.adtech.
fptplay.vn/js/ads.js
.adsplay.net
.mangadex.org/bootstrap/
.vnecdn.net/video/.*?/ads.js
khoai.tv/embed/tracking?
.radsone.com
.yoyo.org/adservers/
.hdslb.com/bfs/static/player/main/widgets/
.phimmoi*.net/js/fx/ga.js
.gstatic.com/docs/common/cleardot.gif?
.google.com/images/cleardot.gif
tracking-protection.cdn.mozilla.net
game-*.granbluefantasy.jp
132.145.124.107
.phucnx.name.vn
.fandom.com/load.php\?debug=
adfs.fpt.com.vn
megaup.net/themes/flow/
.shopee.vn/api/v.*?/
.mangadex.org/_nuxt/
.otofun.net/js/addons/
.otofun.net/css.php?
.otofun.net/styles/
.otofun.net/data/
.dropboxstatic.com/static/
.dropbox.com/web-grpc/

#---------------------------------------
# block tracking MS
{+block{tracking MS}}
# MS
a-000*.a-msedge.net
a-msedge.net
a.ads*.msn.com
a.ads*.msads.net
a.rad.msn.com
ac3.msn.com
ad.sidaAllnet
adnexus.net
adnxs.com
ads.msn.com
ads1.msads.net
ads1.msn.com
aidps.atdmt.com
aka-cdn-ns.adtech.de
az361816.vo.msecnd.net
az512334.vo.msecnd.net
b.ads1.msn.com
b.ads2.msads.net
b.rad.msn.com
bs.serving-sys.com
c.atdmt.com
c.msn.com
cdn.atdmt.com
cds26.ams9.msecn.net
choice.microsoft.com
choice.microsoft.com.nsatc.net
compatexchange.cloudapp.net
corp.sts.microsoft.com
corpext.msitadfs.glbdns2.microsoft.com
cs1.wpc.v0cdn.net
db3aqu.atdmt.com
df.telemetry.microsoft.com
diagnostics.support.microsoft.com
ec.atdmt.com
feedback.microsoft-hohm.com
feedback.search.microsoft.com
feedback.windows.com
flex.msn.com
g.msn.com
h1.msn.com
i1.services.social.microsoft.com
i1.services.social.microsoft.com.nsatc.net
lb1.www.ms.akadns.net
live.rads.msn.com
m.adnxs.com
msedge.net
msftncsi.com
msnbot-65-55-108-23.search.msn.com
msntest.serving-sys.com
oca.telemetry.microsoft.com
oca.telemetry.microsoft.com.nsatc.net
pre.footprintpredict.com
preview.msn.com
rad.live.com
rad.msn.com
redir.metaservices.microsoft.com
reports.wes.df.telemetry.microsoft.com
schemas.microsoft.akadns.net
secure.adnxs.com
secure.flashtalking.com
services.wes.df.telemetry.microsoft.com
settings-sandbox.data.microsoft.com
settings-win.data.microsoft.com
sls.update.microsoft.com.akadns.net
sqm.df.telemetry.microsoft.com
sqm.telemetry.microsoft.com
sqm.telemetry.microsoft.com.nsatc.net
ssw.live.com
static.2mdn.net
statsfe*.ws.microsoft.com
telecommand.telemetry.microsoft.com
telecommand.telemetry.microsoft.com.nsatc.net
telemetry.appex.bing.net
telemetry.microsoft.com
telemetry.urs.microsoft.com
v10.vortex-win.data.microsoft.com
vortex-bn2.metron.live.com.nsatc.net
vortex-cy2.metron.live.com.nsatc.net
vortex-sandbox.data.microsoft.com
vortex-win.data.metron.live.com.nsatc.net
vortex-win.data.microsoft.com
vortex.data.glbdns2.microsoft.com
vortex.data.microsoft.com
watson.live.com
web.vortex.data.microsoft.com
www.msftncsi.com
.microsoft.com/collect/
.data.microsoft.com/OneCollector/
# Extra MS
fe2.update.microsoft.com.akadns.net
s0.2mdn.net
statsfe2.update.microsoft.com.akadns.net
survey.watson.microsoft.com
view.atdmt.com
watson.microsoft.com
watson.ppe.telemetry.microsoft.com
watson.telemetry.microsoft.com
watson.telemetry.microsoft.com.nsatc.net
wes.df.telemetry.microsoft.com
pricelist.skype.com
s.gateway.messenger.live.com
2.22.61.43
2.22.61.66
65.39.117.230
65.55.108.23
23.218.212.69
134.170.30.202
137.116.81.24
157.56.106.189
204.79.197.200
65.52.108.33
64.4.54.254
# Other
.bing.com/manifest/IEOneBox_V2.appcache?

{+suppress-tag{MAXIMUM-URL-LENGTH}}
#.google.
#.gstatic.
#.disqus.com/embed/comments/
#.twitter.com/i/api/2/
#.fandom.com/load.php?
#.facebook.com/ajax/

#---------------------------------------
# block cryptomining
{+block{cryptomining}}
-coin-hive.js
-crypto-miner/*
-monero-miner-
-monero-miner?
-monero-miner/*
/authedmine?
/authedminer.js
/bitcoin-plus-miner/*
/bitcoincore/?ref=
/bootstrap.wasm
/bootstrap.wasm
/browsermine.js
/c-hive.js
/c.wasm
/cloudcoins.js
/cloudcoins.min.js
/cn.wasm?
/coin-hive-proxy-
/coinblind.js
/coinblind_beta.
/coinGofile.
/coinhive-proxy-
/coinhive.min.js
/coinlab.js
/compact_miner?
/crn.wasm
/crypta.js
/crypto-webminer?
/cryptocpu.js
/cryptonight-worker.
/cryptonight.wasm
/cryptonoter.
/deepMiner.js
/deepMiner.min.js
/dprocessor.js
/hash.wasm
/helper.wasm
/inject.js?key=?
/jsecoin.*/?
/lhnhelpouttab-current.min.js
/lib/crlt.js
/media/miner.
/mine/bitcoincore/*
/miner_proxy
/miner-ui.js
/miner.*/crypto-
/miner.*/loader.
/miner.full.js
/miner.js
/miner.min.js
/miner?key=
/minera.js
/minero-proxy-
/minescripts.js
/nano.wasm
/noblock.js
/obfus.min.js
/projectpoi.min.js
/poolstatus?
/safelinkconverter.js
/streambeam-jw.js
/streambeam-video.js
/web_miner/*
/webcoin.js
/webcoin.min.js
/webmr.js
/webxmr.js
/wproxy
/xminer.js
/xminer.min.js
/xmr-monero.js
/xmr.js
/xmr.min.js
.spacepools.
.aspx?poolid=

#----------------------------------------------------------------------------
# Custom
{+block{Custom}}
# Ads services
.*googleadservices.
.*google-analytics.
.*googletagmanager.
.*admicro.
.*doubleclick.
.*scorecardresearch.
.*coin-hive.
.*coinhive.
.*traffic2bitcoin.
.*jsecoin.
# Others
.fuck_off_ads.
www.hayhaytv.vn/vod/info/\w
blueserving.com
.somo.vn
.nitropdf.com/services
/ajax-history-record
widget.weibo.com/public/
open.id.zing.vn/share
.kaolinvieta.com
caosuhoancau.com
up.4share.vn/public/templates/
asiatourguides.info
apps.skype.com/chatadwidget/
ads.pro-market.net
.popads.net
.getlinkinfo.com/info\?
.atas.io
.marathon.mesos.vn
tt.onthe.io
cuguwxkasghy.com
.blueserving.com
.viglink.com
.genieessp.com
pagead*.googlesyndication.com
.juicyads.com
stats.openload.co
.google.com.*/ads/
.google.com/ads/
.doubleclick.
.trafficfactory.
yu987.com
.eclick.vn
.bnserving.com
.nhanthuong88.
.iwanttodeliver.com
.vnexpress.net/trackingvideo.*
log.eclick.vn
adx.kul.vn
.haynhucnhoi.vn
.sw1block.com
.s2block.com
concernrain.com
.addthis.com
.addthisedge.com
.gsspat.jp
.mgid.com
.zencdn.net
.medi-*.net
.userreport.com
.adtech.de
.yomedia.vn
.popclck.net
.ads*adnow.com
.nhanthuong88.com
.jbb512.com
.adglare.net
.4chan-ads.org
.ekansovi.com
.gammaplatform.com
.blueserving.com
.zkcdn.net
.onclkds.com
.xoclkrvstrafms.com
.comodoca.com
linkhay*.vcmedia.vn
.360game.vn
.uniad.vn
sharefb.cnnd.vn
.cpm20.
.advrcsr.
.deployads.com
.beblue.vn/.*.gif
.traffic2bitcoin.
.coin-hive.
.jsecoin.
.pr0gramm.com
.gus.host/coins?
.cnhv.co
patiland.co
.centbrowser.com/user_statistics.*
.ojoku.bigih.bid
bato.to/ads/
.tagcade.com
.gigaonclick.
.velocecdn.
.superfastcdn.
.districtm.io
.hadarone.
delivery.vungtv.com
#entitlements.jwplayer.com
.vidcpm.com
api.voz.vn
.adtrue.com
.pubmatic.com
.fabet.com
.11bet.com
.bong99.com
.mibet.com
adtima-static.zadn.vn
.predocontentdelivery.
ihowed.info
.aaxads.com
.bidgear.com
.contineljs.com
.truex.com
.adtng.com
#supervisor.ext-twitch.tv
.ergeiros.xyz
crvlck.com
.imrworldwide.com
stat.s3blog.org
.octopuspop.com
.anthill.vn
.aimaptair.club
.beiven.pw
logsbin.dantri.com.vn
ftigken.
.upapi.net
alb.reddit.com
.reddit.com/timings/rum
.twitter.com/i/jot
.thofigdot.club
challenge.lotus.vn
trahes.site
cawsodpet.club
ws*.gainskins.com
.adpia.vn
.telemetry.mozilla.org
.demand.supply
.trackpush.com
.dnsdelegation.io
.eulerian.net
.liberation.fr
.gotrack*.es
.runative-syndicate.com
.exdynsrv.com
/(.*/)?event\.gif\?
.baidu.com/.*?gif
.cloudfront.net/.*?gif
24h-img.24hstatic.com/.*?gif
.beblue.vn/.*.gif
.twitch.tv/ping.gif?
.wikia.nocookie.net/.*analytics_js
.phimmoi*.net/js/ambient/client.js
.vid4vip.com
mc.yandex.ru
fvs.io
ouftukoo.net
.makemodernfive11.
.allmobtip.com
in-page-push.com
live.soapps.net
.adskeeper.
.bigexchange.net
.imad24.com
cloud.hitcashtag.com
.dtruyen.com/mobile/js/chapter.js?
.safestcontentgate.com
.pressingmiscellaneoustry.com
.ledslevier.com
.fierceharmlessjacket.com	
.fb88aff.com
.oxbet.
.midastouchrt.com
.ezodn.com
.ezoic.com
.tvhai.org/playergk/.*/vast.js
.mphimmoitv.net/bin.*.js
.mphimmoitv.net/pcAds_.*
.roataisa.net
.amplitudewassnap.com
.outoctillerytor.com
.ashierbowler.com
.rezync.com
.dtadnetwork.com
.closureevaporatefume.com
.doneeinvict.com
.atevaccination.com
.bg4nxu2u5t.com
.clkofafcbk.com
.gliacloud.com
.dable.io
.renomeeguze.com
v9banners.com
.v9bet55.com
.vulnerableimmigrateaboveaverage.com
.adsninja.

{+block{EmtyDocument} +handle-as-empty-document}
anime47.com/js/pop1.js
manga24h.com/popup.js
/show_ads_blueseed.js
.baidu.com/.*?js
extra.sankakucomplex.com/js/default.js
hamtruyen.*/Scripts/ixinh.js
ixinh.net.*/Scripts/
truyentranh8.net/popnewtab.js.*?
adsplay.net/js/
fptplay.net/js/ads.js
blogtruyen.com/Scripts/custom.js
.adtimaserver.vn/resource/js/zads-base-mod.js
blogtruyen.com/Scripts/qctruot2ben.js
.microad.net/js/
.zaloapp.com/za-adtima.js
.microadinc.com/js/
360game.vn/script/gamer-ads.*?
.adtimaserver.vn/resource/js/zad/adr.*?.js
kissanime.to/xyz/check.aspx
.goldpriceoz.net/ads/*
.mediafire.com/templates/linkto/
/antitheft\.php
.kenh14.vn/Statistic/
khaosat.me/embed/doSurvey
tinhte.vn/v2/js/data\.json\?service=Facebook
.zopim.com/s/W/xdds/
.innity.net/admanager.js
webtruyen.com/wp-admin/jsnew/
webtruyen.com/mgid/
.hayhaytv.vn/api/impression_hit?
vozforums.com/clientscript/vbulletin_lightbox\.js?
/vast.js
/[^/]+/vast.js
.fshare.vn/js/adsplay?
.fshare.vn/js/advjs?
.knowlead.io/dmpcollector.js
.truyenfull.vn/ureka/
.mangak.info/.*/ad/
.phimmoi*.net/.*/pad.js
.phimmoi*.net/.*/adoverlay/
.tinhte.vn/js/bdAd/
.hitomi.la/hitomi-.*.js
kisshentai.net/.*betterpop?
.mangarock.com/.*/adtrue.*
.static.hltv.org/.*/csgofast/
.static.hltv.org/.*/hellcase/
.static.hltv.org/.*/ggbet/
.static.hltv.org/.*/lootbet/
.hltv.org/.*php
webtruyen.com/.*/load_video.js
.90phut.tv/assets/.*.js
.90p.tv/js/popup.js?
.hamtruyen.com/.*/ads_.*.js
.webtruyen.com/mobile/js/chapter.js?
/twitch-videoad.js
.mangarock.com/.*/mr.js?
/.*/adblock-checker.*\.js*
.cachefly.net/js/
.redditmedia.com/gtm/jail*
.twitter.com/1.1/jot/client_event.json
.lotuscdn.vn/.*.js
.jwpcdn.com/player/plugins/vast/
cdn.siteswithcontent.com/js/push/
/loader/kiosked-loader.js
#.scdn.co/cdn/js/gtag.
cdnasset.dantri.com.vn/fe/
/scripts/iframe-rand.js?
/scripts/iframe-rand-mobile.js?
.jwpcdn.com/player/plugins/googima/
.thanhnien.vn/services/zone-*..ads
.yeutre.vn/tracking_.?
.isotls.com/detroitchicago/
.pages.dev/.*/vast-30s-ad.xml?
.pages.dev/vast-30s-ad.xml?
.pages.dev/overlay2.xml?
.pages.dev/.*/overlay2.xml?
.jwpcdn.com/player/v/.*/vast.js
.pages.dev/.*/*.gif
/aa/theologicalpresentation.com/
dibsemey.com/pfe/
vizcloud.co/ping/
.imgur.com/*(eB4LTKQ|fhXeUtv|K7x3FrU|WRTmeTC|cwqKUAU|GF5wx3I|8voRVx2|ifgVtSv|8zQHZww|AEOpzFx|XF0aGfI|kBi8btO).gif
.imgur.com/*(?:ZCvsO4D|VxrIb02).mp4
photo*.tinhte.vn/data/attachment-files/.*.-VTM.gif
w3-reporting.reddit.com/reports
.redditstatic.com/shreddit/sentry-
.reddit.com/svc/shreddit/
.twitter.com/i/api/.*/(jot|videoads)/
.thuysanvietnam\.com\.vn[/&:?=_].*\.gif
static.cdnno.com
.metruyencv.com/passback/

{-block{Custom}}
.livechart.me
.lotuscdn.vn/web/v1/js/w.embed.*.js
.cloudfront.net/actions/cheer/.*.gif

{+block{facebook} +handle-as-empty-document}
.g.akamai.net/[^/]+/[^/]+/[^/]+/[^/]+/sp\.ask\.com/i/j/aj7/jscripts/all\.js
.facebook.com/plugins/
.fbcdn.net/connect.
connect.facebook.
#/pull\?
.facebook.com/ads/
error.facebook.com
#/ping\?
#/p\?
#/ajax/bz
#/ajax/mercury/
#/ajax/mercury/change_read_status.php 
#/ajax/pagelet/generic.php/WebEgo
/ajax/.*?/logging/
#/xti.php
#/ajax/typeahead
#/ajax/presence/reconnect
#/ajax/browse/null
#/ajax/timeline/collections/
/ajax/lifestand/
#/ajax/timeline/load_more
/.*?tags_init
#/si/kappa/
#/ai.php\?
#/safe_image.php
#.fbcdn.net/rsrc.php
.facebook.com/xti.php\?
/sem_pixel_test/\?
pixel.facebook.com

{-block{facebook}}
.facebook.com/ajax/feed/filter_action/dialog_direct_action_ads\?dpr=1
.fbcdn.net/rsrc.php?
.facebook.com/ajax/pagelet/

{+block{Youtube-GG}}
#.google.com/client-channel/client.*?yt-live-comments
#.youtube.com/live_stats
#.youtube.com/live_
youtube.com/.*?adserver
youtube.com/.*?_ads
#/_/scs/.*?iframes
www.google.com/jsapi\?autoload=
.youtube.com/api/stat
youtube.com/.*?-ads
#.youtube.com/ptracking
#www.google.com/js/bg/
.google./.*?gen_204
.ytimg.com/.*?gen_204
.gstatic.com/gen_204
.youtube.com/gen_204
.youtube-nocookie.com/gen_204
/generate_204
.youtube.com/player_2
.ytimg.com/.*?204
#.ytimg.com/sb
.youtube.com/annotations_invideo
.youtube.com/gen_*?a=resolution&width
.youtube.com/get_midroll_
.youtube.com/get_video_*el=adunit*
.youtube.com/sw.js
.youtube.com/yts/jsbin/serviceworker-notifications-*

{-block{Youtube-GG}}
.google.com/client
gdata.youtube.com
.youtube.com/feed_change_ajax
.youtube.com/.*?frags=comments
.youtube.com/comment_service_ajax?
.youtube.com/api/stats/atr
.youtube.com/api/stats/playback?
.youtube.com/api/stats/watchtime?