#-------------------------------------------------------
#---------------------------------------
# Initialize
{{alias}}
+bypass    = -crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects -hide-referer	
+bypassall = -block -crunch-incoming-cookies -crunch-outgoing-cookies -filter -fast-redirects -hide-referer

#---------------------------------------
# +
{+bypass}
#MS
otf.msn.com
.microsoft.com
.microsoft.net
.1drive.com
.windowsupdate.com
.mesh.com
ssl.bing.com
services.msn.com
.1drive.com
.hotmail.com
.windows.net
.livefilestore.com
.xboxlive.com
.platform.bing.com
.bing.com/speech_render.*?
clientlogin.cdn.skype.com
.vo.llnwd.net/hls/
.outlook.com/Microsoft-Server-ActiveSync?
eas.outlook.com
trouter.io/socket.io/
.apps.skype.com/comscore/index.html\?event=Message*?
.tiles.virtualearth.net
#GG
chrome.google.com
clients*.google.com
drive.google.com
mail.google.com
accounts.google.com
docs.google.com
fonts.google.com
i.ytimg.com
.twimg.com
.google.com/recaptcha/
fonts.googleapis.com/css\?
.gstatic.com/recaptcha/
.google.com/carddav/
.googleusercontent.com/caldav/
.youtube.com/.*?frags=comments
.googleapis.com
#OT
regex101.com
sync.services.mozilla.com
sync.opera.com
.paypal.com
.ebank.tpb.vn
.vietcombank.com.vn
.audioscrobbler.com
.steampowered.com/depot/
.contrejour.ie
kjllmeplz.wordpress.com
kjllmeplz.files.wordpress.com
.xml.weather.com/weather/
mail.fpt.com.vn
checkip.dyndns.org
.githubusercontent.com/kjllmeplz/.*?\.(gif|GIF|jpg|js)$
.allmusic.com/search/
.last.fm/music/.*?\+wiki$
.search.dongting.com/song/search/
.so.ard.iyyin.com/s/song_with_out\?
.lp.music.ttpod.com/lrc/down\?lrcid
.ttlrcct.qianqian.com/dll/
.music.163.com/api/
forums.e-hentai.org
.steamcontent.com
home.scpd.live/client/
fpt.com.vn/AutoDiscover/
.dsvn.vn
.muachung.vn/.*?act=cart

{+bypassall}
.privoxy.org
p.p
.googlevideo.