# Only for mobile
{+forward-override{forward 127.0.0.1:8085}}
.medium.com
.xvideos.com
.pornhub.
.hanime.
.nhentai.
.tiengruoi.link
.*tiengruoi.link
.1h30m.
.bongdaso.
.bongdaso*.
.90phutt.
.90phut*.
.truyenmot.xyz
.sapfans.com
.twitchearnings.com
.phimmoi.net
.xamvn.
.voz.vn