#----------------------------------------------------------------------------
# Settings -- Don't change
{{settings}}
for-privoxy-version=3.0.30

#----------------------------------------------------------------------------
# Aliases
{{alias}}
# Default
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}

# Global filter
# Banner
+banner-filter      = +filter{float-ck} \
		      +filter{banners-by-link} \
		      +filter{banners-by-size}
# Tracking
+tracking-filter    = +filter{no-ping} \
		      +filter{img-reorder} \
		      +filter{jumping-windows} \
		      #+filter{blockwebrtc} \
		      #+filter{refresh-tags} \
		      +filter{webbugs}
# All
+global-filter      = +filter{injection} \
		      +banner-filter \
		      +tracking-filter \
		      +filter{doubleclick} \
		      +filter{Troll}

# Bypass filter
-banner-filter      = -filter{float-ck} \
		      -filter{banners-by-link} \
		      -filter{banners-by-size}

-tracking-filter    = -filter{blockwebrtc} \
		      -filter{no-ping} \
		      -filter{webbugs} \
		      -filter{img-reorder} \
		      -filter{jumping-windows} \
		      -filter{refresh-tags}
		      
-global-filter      = -filter{injection} \
		      -banner-filter \
		      -tracking-filter \
		      -filter{doubleclick} \
		      -filter{Troll}

#----------------------------------------------------------------------------
# Golbal settings

#-------------------------------------------------------
# SSL Filter
{+https-inspection}
:443

# Default settings + Add by kjll 
{ \
#+change-x-forwarded-for{block} \
+server-header-tagger{content-type} \
+server-header-tagger{content-length} \
+client-header-tagger{css-requests} \
+client-header-tagger{image-requests} \
+client-header-tagger{range-requests} \
#+client-header-tagger{url} \
#+client-header-tagger{tagger4https} \
#+client-header-tagger{websocket} \
#+client-header-tagger{maximum-url-length} \
+client-header-tagger{maximum-domain-length} \
+global-filter \
#+hide-referer{forge} \
#+hide-from-header{block} \
#+hide-referrer{conditional-block} \
#+set-image-blocker{pattern} \
}
/

#-------------------------------------------------------
# Cautious settings
#
{ \
#+change-x-forwarded-for{block} \
#+client-header-tagger{css-requests} \
#+client-header-tagger{image-requests} \
#+client-header-tagger{range-requests} \
+deanimate-gifs{last} \
+filter{refresh-tags} \
+filter{img-reorder} \
#+filter{banners-by-size} \
#+filter{webbugs} \
+filter{jumping-windows} \
+filter{ie-exploits} \
+hide-from-header{block} \
#+hide-referrer{conditional-block} \
+session-cookies-only \
+set-image-blocker{pattern} \
+overwrite-last-modified{randomize} \
+crunch-if-none-match \
}
standard.Cautious
firstpartysimulator.org

#-------------------------------------------------------
# Advanced settings
#
{ \
+change-x-forwarded-for{block} \
+client-header-tagger{css-requests} \
+client-header-tagger{image-requests} \
+client-header-tagger{range-requests} \
+crunch-if-none-match \
+crunch-outgoing-cookies \
+crunch-incoming-cookies \
+deanimate-gifs{last} \
+fast-redirects{check-decoded-url} \
+filter{html-annoyances} \
+filter{content-cookies} \
+filter{refresh-tags} \
+filter{img-reorder} \
+filter{banners-by-size} \
+filter{banners-by-link} \
+filter{webbugs} \
+filter{jumping-windows} \
+filter{frameset-borders} \
+filter{quicktime-kioskmode} \
+hide-if-modified-since{-60} \
+hide-from-header{block} \
+hide-referrer{conditional-block} \
#+limit-connect{,} \
+overwrite-last-modified{randomize} \
+set-image-blocker{pattern} \
}
standard.Advanced
ip-check.info

#----------------------------------------------------------------------------
# Specific settings

#-------------------------------------------------------
# Ignore error on certificate
{+ignore-certificate-errors}
.privoxy.org

# Custom
#-------------------------------------------------------
# Block DF by ads4
{+block{kjll_ads4}}
.fuck_off_ads.

#-------------------------------------------------------
# Handle by file types
#---------------------------------------
# These extensions belong to images:
{+handle-as-image -filter}
/.*\.(gif|jpe?g|png|bmp|ico)($|\?)
#---------------------------------------
# These don't:
{-handle-as-image}
/.*\.(js|php|css|.?html?)
#---------------------------------------
# These belong to multimedia files
{-filter -deanimate-gifs}
/.*\.og[gv]$

#-------------------------------------------------------
# Allow referer
{-hide-referer{forge}}
validator.w3.org/check\?uri=referer
.petitiononline.com/mod_perl/signed.cgi
.telia.se
schneegans.de/sv/\?url=referer
vod-*.phimmoicdn.net/v1.0/
vod.*.phimmoicdn.net/v1.0/
pzc.phimmoi.net/embed/
pzc.phimmoi*.net/embed/

{-hide-referrer{conditional-block}}
.cdndm5.com
cdn.lhmanga.com

{-hide-referer}
.googleapicdn.com

#-------------------------------------------------------
# Allow permanent cookies
{allow-all-cookies}
.exhentai.org
.e-hentai.org

{-session-cookies-only}
.nytimes.com
.volkskrant.nl

#-------------------------------------------------------
# Accept popups
{allow-popups}
www.aprilbarrows.com/discography\.html$
.nvidia.com
www*.chathouse.com/games/
.bild.t-online.de
.netflix.com
my.aol.com
i.cnn.net/cnn/.*/clickability/button
.rosettaproject.org
.quantum.com
.liberation.fr

#-------------------------------------------------------
# Fast-redirects catches things by mistake
{-fast-redirects}
www.ukc.ac.uk/cgi-bin/wac\.cgi\?
.google.*
.altavista.com/(.*(like|url|link):|trans.*urltext=)http
.speedfind.de
.nytimes.com
.yahoo.com/
.w3.org
.directhit.com
.zagats.com
my.msn.com/passport/pp(consent|set)\.ashx\?msnru=
www.passport.com/Consumer/default\.asp\?lc=[0-9]+&msppchlg=[01]&mspplogin=
login.passport.com/logout\.(asp|srf)\?
download.com.com/redir\?
www.fileplanet.com/redir\.asp\?
.edu
.archive.org
www.guenstiger.de
.anonymizer.com
www.mailtothefuture.com
support.microsoft.com/
.alexa.com
www.translate.ru/url/
schneegans.de/
config.privoxy.org/
.wsj.com/lmda/do/checkLogin
del.icio.us/
.ctv.ca/.*&site_cfcn=http://
.informit.com/.*&r=http%3a%2f%2f
access.adobe.com/access/getStatus.do\?jobid=&srcPdfUrl=
view.samurajdata.se/ps\.php\?url=
.blogger.com/navbar\.g
.dmoz.org/editors/editurl\.cgi
.ebay.de/ws/eBayISAPI\.dll\?
.amazon.com/gp/redirect.html/.*location.*&token
.groundspring.org/
.landsend.de/
.youtube.com/swf/.*swf=
.redbot.org/
webcache.googleusercontent.com/
.googleusercontent.com/.*=cache:
.googleapis.com/
.google./sorry/\?continue?=
.microsofttranslator.com/
.facebook.com/plugins/like.php
creativecommons.org/
ixquick-proxy.com/
.anime47.com

#-------------------------------------------------------
# Specific Action

{+hide-user-agent{Nothing}}
.checkip.org
browserleaks.com

{+server-header-filter{cors}}
# Facebook video on FF
#.facebook.com
video.*.fbcdn.net
video-*.*.fbcdn.net
video.*.*.fbcdn.net
apiif-tvhai.rdgogo.xyz
play.tvhaystream.xyz
#.global.cdnfastest.com
#

{+server-header-filter{cors_csstats}}
.csgostats.gg
.csstats.gg

{+server-header-filter{bettercache}}
#

{+server-header-filter{removecontentsecuritypolicy}}
#.twitter.com

{+add-header{Access-Control-Allow-Origin: *}}
#

{+client-header-filter{reddit-image}}
i.redd.it
preview.redd.it

{+server-header-filter{privoxycsp}}
.facebook.com
#.twitter.com
.#x.com

{+server-header-filter{privoxyjs}}
#config.privoxy.org/.*?\.js$

{+content-type-overwrite{application/xml}}
config.privoxy.org/.*?\.js$

{+add-header{Referer: https://www.youtube.com/}}
#.youtube.com/watch?

{+add-header{Origin: https://www.youtube.com}}
#.youtube.com/watch?

{+hide-user-agent{Mozilla/5.0 (Windows Phone 10.0; Mobile; rv:107.0) Gecko/107.0 Firefox/107.0}}
#.youtube.com

{+hide-user-agent{Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.3}}
maps.google.com
.youtube.com

{+hide-user-agent{Nothing} -crunch-incoming-cookies -crunch-outgoing-cookies}
.ip-check.info

{+downgrade-http-version}
:631

# Redirect
{+redirect{http://config.privoxy.org/}}
#config.privoxy.org:443
#.privoxy.org/config/
#p.p

{+redirect{https://www.ghacks.net/}}
#genk.vn

{+redirect{https://www.gematsu.com/}}
#gamek.vn

{+redirect{s@&player_type=site@&player_type=embed@}}
api.twitch.tv/api/channels/.*/access_token\?.*&player_type=site

{+redirect{s@^https://[^/]*/(.*)@http://old.reddit.com/$1@}}
reddit.com
www.reddit.com

# Disable compression
{+prevent-compression}
#.fandom.
#.hltv.org
#.90phut.
#.90phut*.
#.90m.
#.90p.
#.binhluanvidamme.
#.binhluanvidamme*.
#.phut90.
#.phut91.
#90.*.link
#mitom.*.link
#.90phutt.
#.thapcam.

#----------------------------------------------------------------------------
# Sections that reject global filter

#---------------------------------------
# Specific filter

{-filter{injection}}
cdnssl.mediafire.com
apifree.forvo.com/key
.nocookie.net
.softpedia-static.com

{-filter{noopenpopup}}
kuteteen.tv
.youtube.com

{-filter{float-ck}}
.deviantart.
.hayhaytv.vn
.google.
.twitch.tv
.youtube.com
4pda.ru
.hanime.tv
.anichart.net
.softpedia.com
.xda-developers.com
.windowscentral.com
.hamtruyen.vn
.cgv.vn
truyentranhlh.com
.reddit.com
.otofun.net

{-filter{banners-by-size}}
.pricegrabber.com/search_getprod.php
.gamespot.com/gamespot
www.wral.com
.cartoonnetwork.com/
.anybrowser.org
images.google.
.pbs.org/.*/roadshow/
objects.povworld.org/cat/
www.xach.com/gimp/
.mapquest.com/directions/
.theonion.com/content/
.pattilupone.net/gallery.html
.ambrosiasw.com/
.microsoft.com
javabog.dk/ijk/
.w3.org
.encyclopediadramatica.com/
.ikea.com/
.froscon.de/
.fsfe.org/
.couchsurfing.com/
.couchsurfing.org/
.thinkgeek.com/
.dgb-tagungszentren.de/
creativecommons.org/
kggp.de/
.dantri.com.vn
.hanime.tv
.cgv.vn
.otofun.net

{-filter{banners-by-link}}
.wikia.com
.fandom.com
.pixiv.net
.otofun.net

{-filter{webbugs}}
.fptplay.vn

{-filter{img-reorder}}
tinhte.vn
gamepress.gg

{-filter{doubleclick}}
#

{-filter{Troll}}
.facebook.com
.4pda.ru
.gsmarena.com
.notebookcheck.net
.wp.com
.inet.vn
.pibook.vn
.vanminh76.vn
.tiki.vn
.shopee.vn
.vexere.com
.nhaphangtrungquoc247.vn
itsgl.backlog.com
playzone.vn

{-redirect{s@^https://[^/]*/(.*)@http://old.reddit.com/$1@}}
.reddit.com/media?
i.redd.it
preview.redd.it
.reddit.com/gallery/

#---------------------------------------
# Exception all

{-banner-filter}
api.skype.com
.liquipedia.net
.reddit.com
.bilibili.com

{-banner-filter -tracking-filter}
.facebook.com
.exhentai.org
.hanoicomputer.vn
.honeyhunterworld.com
.vuighe.net
.mphimmoitv.net

{-global-filter}
# Tag
NO-RESPONSE-TAG:^text/html
#TAG:^(application|text)/(x-)?javascript$

# Sites
vcplayer.mediacdn.vn
liveupdate.symantec.com
liveupdate.liveupdatesymantec.com
liveupdate.symantecliveupdate.com
.bookmarklets.com
.squarefree.com/bookmarklets/
swquery.apple.com
swscan.apple.com
.speakeasy.net/\d+k
.debian.org
bugzilla.
.tldp.org
webmail.
.*wiki.
.wiktionary.org/
maps.google.
.google.com/(calendar|reader)
code.
developer.
.mozdev.org
.mozilla.org
.perl.org
.cpan.org
.webdeveloper.com
.ibm.com/developerworks
.apache.org/docs
.comptechdoc.org
.webmonkey.com
.webreference.com
.sun.com
.thescripts.com
.php.net
.phpdeveloper.org
.oreillynet.com/pub
.devshed.com
.htmlgoodies.com
.javascript.com
javascript.internet.com
.w3schools.com
.devguru.com
javascriptkit.com
.xulplanet.com
.perl.com/language/newdocs
.freebsd.org
.watson.org
.netbsd.org
.openbsd.org
.dragonflybsd.org
.freedesktop.org
.gnu.org
.fedoraproject.org
.userscripts.org
.jpl.nasa.gov
#
/(.*/)?flyspray/
/(.*/)?mail(man|archive|inglists?)/
bugs.
quoka.de
#
.facebook.com/ajax/
static.*.fbcdn.net
aceship.github.io
#
mphimmoitv.net/ajax/