#---------------------------------------
# Initialize

{{alias}}
# Exclude all js filter
-jsfilter =  -filter{GMFunction} -filter{LongRunCPU} \
  	     -filter{CanvasBlocker} -filter{GreasyForkjs}

#---------------------------------------
# Global

#-------------------
# +


#-------------------
# -


#---------------------------------------
# Specific

#-------------------
# +

{+filter{GreasyForkjs}}
.greasyfork.org/.*?\.js

{+filter{CanvasBlocker}}
#/

#-------------------
# -

{-jsfilter}
TAG:^(application|text)/(x-)?javascript$

{-filter{CanvasBlocker}}
.facebook.com
.regex101.com
.blogtruyen.vn
.twist.moe
.phimmoi*.net
.hltv.org
.voz.vn
.horriblesubs.info
.90p.tv
.sap.com
.tinhte.vn
.reddit.com
nhentai.net
.google.com/maps/
.twitch.tv