#---------------------------------------
# Initialize

{{alias}}
-jsfilter =  -filter{GMFunction} \
  	     -filter{EnableRightClick} -filter{canvasblocker} -filter{greasyforkjs} \
	     -filter{unloadonnotfocus} -filter{antiredirecttrack} \
	     -filter{YouTubePlus} -filter{BypassYouTubeAge} \
	     -filter{MaknyosAutoIn} -filter{AdsBypass} \
	     -filter{FacebookUnsponsored} -filter{kissscript} \
	     -filter{MangaLoaderNSFW} -filter{MangaLoader}

#---------------------------------------
# Global

#-------------------
# +


#-------------------
# -


#---------------------------------------
# Specific

#-------------------
# +

{+filter{EnableRightClick}}
.senmanga.
.mangarock.com
.fullcrackpc.com
.exhentai.org

{+filter{canvasblocker}}
.browserleaks.com

{+filter{greasyforkjs}}
.greasyfork.org/.*?\.js

{+filter{GMFunction} +filter{YouTubePlus}}
#.youtube.com

{+filter{GMFunction} +filter{Iridium}}
#.youtube.com

{+filter{GMFunction} +filter{BypassYouTubeAge}}
#.youtube.com/verify_age.*
#.youtube.com/verify_age.*
#.youtube.com/verify_controversy.*
#.youtube.com/verify_controversy.*
#.youtube.com/watch.*
#.youtube.com/watch.*
#.youtube.com

{+filter{FacebookUnsponsored}}
.facebook.com

{+filter{Openload-JS}}
openload.co
.openload\.co\/.*..*/

{+filter{twitchads}}
.twitch.tv

{+filter{noopener}}
#/

{+filter{GMFunction} +filter{MangaLoader}}
.bato.to/reader.*
.mangafox.*/manga/
.readms.net/r/
.mangastream.com/r/
.mangastream.com/read/
.www.mangareader.net/
.mangahere.co/manga/
.www.mangapanda.com/
.mangapark.me/manga/
.mngcow.co
.centraldemangas.org/online/
.com.br/leitura/online/capitulo/
.www.mangatown.com/manga/
.manga-joy.com
.dm5.com/m.*
.senmanga.com
.www.japscan.com/lecture-en-ligne/
.www.pecintakomik.com/manga/
.mangawall.com/manga/
.manga.animea.net
.kissmanga.com/Manga/
.view.thespectrum.net/series/
.manhua.dmzj.com
.hqbr.com.br/hqs/.*/capitulo/.*/leitor/0
.www.dmzj.com/view/
.mangaindo.id
.mangadoom.co
.mangago.me/read-manga/
.mangalator.ch/show.php\?gallery=.*
.eatmanga.com/Manga-Scan/
.www.mangacat.me
.www.mangahen.com
.www.readmanga.today
.mangatraders.biz/read-online/
.www.mangainn.net/manga/chapter/
.kukudm.com/comiclist/
.www.mangamap.com
.www.mangachapter.me/.*.html
.kawaii.ca/reader/
.lonemanga.com/manga/
.read.egscans.com/om/manga/
.manga.madokami.al/reader/
.read.egscans.com
.imperialscans.com/read/
.www.chuixue.com/manhua/
.www.sh-arab.com/manga/
.spinybackmanga.com
.br.mangahost.com/manga/
.www.manga.ae
.mangaforall.com/manga/
.hellocomic.com/
.www.3asq.info/
.readcomiconline.to/Comic/
.moonbunnycafe.com
.mangaeden.com
.comicastle.org/read-.*
.mymh8.com/chapter/
.unionmangas.net/leitor/
.otakusmash.com/
.mangahome.com/manga/
.readcomics.tv/.*/chapter.*
.cartoomad.com/comic/
.ikanman.com/comic/
.mangasail.com
.mangatail.com
.titaniascans.com/reader/
.komikstation.com
.gmanga.me/mangas/
.manga.redhawkscans.com/reader/read/
.reader.s2smanga.com/read/
.casanovascans.com/read/
.reader.vortex-scans.com/read/
.reader.roseliascans.com/read/
.mangatopia.net/slide/read/
.www.twistedhelscans.com/read/
.sensescans.com/reader/read/
.reader.kireicake.com/read/
.substitutescans.com/reader/read/
.mangaichiscans.mokkori.fr/fs/read/
.reader.shoujosense.com/read/
.www.friendshipscans.com/slide/read/
.manga.famatg.com/read/
.www.demonicscans.com/FoOlSlide/read/
.reader.psscans.info/read/
.otscans.com/foolslide/read/
.necron99scans.com/reader/read/
.manga.inpowerz.com/read/
.reader.evilflowers.com/read/
.reader.cafeconirst.com/read/
.kobato.hologfx.com/reader/read/
.abandonedkittenscans.mokkori.fr/reader/read/
.jaiminisbox.com/reader/read/
.gomanga.co/reader/read/
.reader.manga-download.org/read/
.manga-ar.net/manga/
.helveticascans.com/reader/read/
.helveticascans.com/r/read/
.reader.thecatscans.com/read/
.yonkouprod.com/reader/read/
.championscans.com/read/
.whiteoutscans.com/read/
.hatigarmscans.eu/hs/read/
.kirishimafansub.com/lector/read/
.hotchocolatescans.com/fs/read/
.slide.world-three.org/read/

{+filter{GMFunction} +filter{MangaLoaderNSFW}}
.dynasty-scans.com/chapters/
.hentaifr.net
.prismblush.com/comic/
.hentairules.net/galleries.*/picture.php.*
.pururin.us/view/
.hitomi.la/reader/
.doujins.com
.www.8muses.com/comix/picture/
.nowshelf.com/watch/
.nhentai.net/g/
.e-hentai.org/s/
.exhentai.org/s/
.fakku.net/
.hentaihere.com/m/
.www.hentaihere.com/m/
.tsumino.com/Read/View/
.www.hentaibox.net/
.hentai-free.org/
.mangafap.com/image/
.hentai4manga.com/hentai_manga/
.heymanga.me/manga/
.simply-hentai.com/.*/page/
.gameofscanlation.moe/projects/
.luscious.net/c/.*/pictures/album/.*/id/
.hentaifox.com/g/
.hentai2read.com/
.hentai.ms/manga/
.reader.yuriproject.net/read/
.ecchi.japanzai.com/read/
.h.japanzai.com/read/
.reader.japanzai.com/read/
.yomanga.co/reader/read/
.raws.yomanga.co/read/
.hentai.cafe/manga/read/
.yuri-ism.net/slide/read/

{+filter{GMFunction} +filter{ExHlogin}}
#.exhentai.org

{+filter{GMFunction} +filter{MaknyosAutoIn}}
(files|maknyos).indowebster.com
.2shared.com/file
.zippyshare.com
.mediafire.com/(download|view|file)
.sendspace.com/file?
.uptobox.com
.howfile.com/file?
.uppit.com
.imzupload.com
.jumbofiles.com
.sendmyway.com
.tusfiles.net
.dropbox.com/s
.solidfiles.com
.yadi.sk
.datafilehost.com/d
.userscloud.com
.hulkload.com
app.box.com/s
.dailyuploads.net
.kumpulbagi.id
.kbagi.com
.kb.simple-aja.info
.moesubs.com/url
kirino.ga/lak
.kirino.sexy
.seiba.ga
.mylinkgen.com
.openload.co
.rgho.st
.uploadrocket.net
.(upload.so|uplod.ws)
.upload.ee/files
.uploads.to
.uploadbank.com
.drop.me
.dropapk.com
up.top4top.net
cloud.mail.ru/public
drive.google.com/file/
docs.google.com/uc\\?.*/
bc.vc
sh.st
adf.ly
adfoc.us
my.pcloud.com/publink
filescdn.com
gen.lib.rus.ec
libgen.io
golibgen.io
bookzz.org
.bookfi.net

{+filter{GMFunction} +filter{AdsBypass}}
.01.nl
.08lkk.com
.0img.net
.10co.biz
.10co.co
.10co.me
.10co.xyz
.123link.top
.18pron.ru
.1be.biz
.1dl.biz
.1pics.ru
.1tiny.net
.1tk.us
.244pix.com
.24avarii.ru
.2i.cz
.2i.sk
.2imgs.com
.2ty.cc
.365-img.com
.3ra.be
.4fun.tw
.a.pomf.se
.abload.de
.ad2links.com
.ad4.fr
.ad5.eu
.adb.ug
.adbla.us
.adcrun.ch
.adf.ly
.adfe.es
.adfoc.us
.adjet.biz
.adjet.eu
.adlink.guru
.adlock.org
.adlot.us
.admy.link
.ads-img.info
.adtr.im
.adultimg.org
.adultmove.info
.adurl.id
.adwat.ch
.adyou.me
.ah-informatique.com
.ah.pe
.aka.gr
.akoam.com
.al.ly
.all-poster.ru
.allanalpass.com
.allkeyshop.com
.ally.sh
.amankan.link
.amateurfreak.org
.amy.gs
.anafile.com
.ani-share.com
.anisubsia.tk
.anonpic.com
.anonymbucks.com
.any.gs
.apploadz.ru
.arab.sh
.atu.ca
.auto14.pw
.autofans.pw
.avenuexxx.com
.awaremmxv.com
.awsubs.cf
.azhie.net
.b4he.com
.bat5.com
.bayimg.com
.bc.vc
.beeimg.com
.biglistofwebsites.com
.bild.me
.bilder-space.de
.bilder-upload.eu
.bildr.no
.binbox.io
.blackcatpix.com
.blogspot.com
.bokimage.com
.bol.tl
.boxcash.net
.bulkimg.info
.bunnyforum.org
.buzurl.com
.cash4files.com
.casimages.com
.catcut.net
.cdn.javtotal.com
.celebclk.com
.cf.ly
.cf2.me
.cf3.me
.cf5.me
.cf6.co
.cf7.co
.chronos.to
.clb1.com
.cli.gs
.clickthru.ca
.clictune.com
.clk.im
.cocoleech.com
.coeg.in
.coinlink.co
.coinurl.com
.comicon.com.br
.compul.in
.comyonet.com
.coolrom.com
.coreimg.net
.crd.ht
.croco.me
.croco.site
.croftimage.com
.cshort.org
.cubeupload.com
.cun.bz
.cur.lv
.cuteimg.cc
.cuzle.com
.cvc.la
.cypt.ga
.d69.in
.daily-img.com
.dailyss.net
.damimage.com
.dapat.in
.darpix.desi
.darpix.ga
.dd.ma
.deb.gs
.decrypt.safelinkconverter.com
.depic.me
.dereferer.website
.designinghomey.com
.detonating.com
.dewaurl.com
.dh10thbvu.com
.digg.to
.dikit.in
.dimtus.com
.directupload.net
.disingkat.in
.dl-protect.com
.dl.nsfk.in
.dlneko.com
.dlneko.net
.dlneko.org
.dmus.in
.domaink.ru
.dragimage.org
.drstickyfingers.com
.dumppix.com
.durl.me
.dwimg.com
.dyo.gs
.easyurl.net
.edogawa.lon.pw
.ehdwallpapers.org
.eightteen.com
.elde.me
.elink.link
.embedupload.com
.empireload.com
.emptypix.com
.ericsony.com
.erimge.com
.ethi.in
.euro-pic.eu
.ex9.co
.fapat.me
.fapingpics.com
.fapoff.com
.fas.li
.fastpic.ru
.fastpics.net
.filesbucks.com
.filesonthe.net
.filmku.lompat.in
.filoops.info
.firedrive.com
.fit.sh
.fiuxy.co
.fly2url.com
.forbes.com
.fotolink.su
.fotoo.pl
.fotosik.pl
.fotoszok.pl
.foxyimg.link
.freakimage.com
.free-tv-video-online.info
.freean.us
.freeanimeonline.xyz
.freebunker.com
.freegaysitepass.com
.freeimage.us
.freeimgup.com
.freephotohostin.com
.fuestfka.com
.fullimg.com
.fundurl.com
.funextra.hostzi.com
.funimg.net
.funkyimg.com
.g5u.pw
.gadget13.com
.gadget14.pw
.galleries.bz
.gallerycloud.net
.gallerynova.se
.gallerysense.se
.gca.sh
.getcomics.gq
.ghanaimages.co
.gkurl.us
.go2.me
.goimagehost.com
.goimg.xyz
.goimge.com
.golfpit.net
.goneviral.com
.goolink.me
.goshrink.com
.goto.loncat.in
.gratisimage.dk
.greasyimage.com
.greenpiccs.com
.gsurl.me
.gtaind.com
.gunting.in
.gunting.web.id
.gx.si
.gxp.so
.h-animes.info
.healthygress24.ga
.hentai-baka.com
.hentai-hosting.com
.hentai-hot.xyz
.hentai-king.host
.hentai-king.online
.hentai-pop.com
.hentaimg.com
.hit.us
.holdthemoan.net
.hornywood.tv
.hostingfailov.com
.hostingpics.net
.hostpic.org
.hosturimage.com
.hotchyx.com
.hotimage.uk
.hotimages.eu
.hotshorturl.com
.hulkimge.com
.i.hentai-ddl.org
.ichan.org
.idsly.com
.ifap.co
.ifotos.pl
.igg-games.co
.igg-games.com
.ilix.in
.ilovebanten.com
.ima.so
.imadul.com
.image.adlock.org
.image18.org
.image2you.ru
.imagearn.com
.imagebam.com
.imageban.net
.imageban.ru
.imageberyl.com
.imagebic.com
.imagecarry.com
.imagecherry.com
.imagecorn.com
.imagecrest.com
.imagecurl.com
.imagecurl.org
.imagedecode.com
.imagedomino.com
.imagedunk.com
.imageeer.com
.imagefolks.com
.imagefruit.com
.imageheli.com
.imagehorse.com
.imagehousing.com
.imagelaser.net
.imageleon.com
.imagenetz.de
.imageno.com
.imagenpic.com
.imageon.org
.imageontime.com
.imagep2p.com
.imagepearl.com
.imagepicsa.com
.imagepix.org
.imagepong.info
.imageporn.eu
.imageporter.com
.imagerar.com
.images.maxigame.by
.imagescream.com
.imageshack.us
.imageshost.ru
.imageshots.com
.imagesnake.com
.imagesnake.org
.imagesouls.net
.imagestime.com
.imageswitch.com
.imageteam.org
.imagetwist.com
.imageup.ru
.imageupper.com
.imagevau.eu
.imagevenue.com
.imageview.me
.imagezilla.net
.imagik.fr
.img-365.com
.img-hentai.host
.img-king.xyz
.img-pay.com
.img-planet.com
.img-pop.info
.img-uploads.com
.img-view.net
.img-zone.com
.img.3ezy.net
.img.deli.sh
.img.pornleech.com
.img.spicyzilla.com
.img.yt
.img1.imagilive.com
.img22.com
.img24.org
.img2share.com
.img3x.com
.img3x.net
.img4sharing.com
.imgadult.com
.imgbabes.com
.imgban.com
.imgbar.net
.imgbb.net
.imgbeer.com
.imgbin.me
.imgbinbou.com
.imgblank.com
.imgblow.com
.imgboom.net
.imgbox.com
.imgcandy.net
.imgcarry.com
.imgcentral.com
.imgchili.com
.imgchili.net
.imgclick.net
.imgcloud.co
.imgcoin.net
.imgcover.com
.imgcream.com
.imgcurl.com
.imgdevil.com
.imgdew.com
.imgdiamond.com
.imgdino.com
.imgdollar.com
.imgdomino.com
.imgdragon.com
.imgdream.net
.imgdrive.co
.imgdrive.net
.imgease.re
.imgfantasy.com
.imgfap.net
.imgfapper.com
.imgfiles.org
.imgflare.com
.imggold.org
.imghere.net
.imghit.com
.imgicy.com
.imgkicks.com
.imgking.co
.imgkings.com
.imgleech.com
.imglemon.com
.imgload.me
.imgmag.co
.imgmaid.net
.imgmain.com
.imgmaster.net
.imgmaze.com
.imgmega.com
.imgmonkey.com
.imgnemo.com
.imgnext.com
.imgnimz.com
.imgnip.com
.imgnm.net
.imgnova.xyz
.imgoutlet.com
.imgpaying.com
.imgpix.net
.imgplus.ru
.imgprime.com
.imgproject.net
.imgpu.com
.imgpython.net
.imgrat.com
.imgreputa.com
.imgrock.net
.imgrun.net
.imgsavvy.com
.imgsay.com
.imgsee.me
.imgseed.com
.imgseeds.com
.imgsen.se
.imgsense.com
.imgserve.net
.imgshots.com
.imgsilo.net
.imgsin.com
.imgslip.com
.imgsmile.com
.imgsoo.net
.imgspice.com
.imgspot.org
.imgstudio.org
.imgsure.com
.imgtaxi.com
.imgtheif.com
.imgtiger.com
.imgtiger.org
.imgtor.pw
.imgtornado.com
.imgtown.net
.imgtrex.com
.imgtrial.com
.imgtube.net
.imgtwyti.com
.imgtzar.com
.imgult.com
.imguniversal.com
.imgurban.info
.imgurx.net
.imgvault.pw
.imgve.com
.imgview.net
.imgwallet.com
.imgwet.com
.imgxyz.net
.imgz.pw
.imgzap.com
.imgzeus.com
.imgzizi.xyz
.imzdrop.com
.indexmovie.xyz
.insurance1.tech
.iori.us
.ipic.su
.ipicture.su
.ironimg.net
.itmages.ru
.itw.me
.ity.im
.jav-hentai.host
.javcity.com
.javelite.tk
.javtotal.com
.jheberg.net
.jnw0.com
.kazan.vc
.keptarolo.hu
.kingofshrink.com
.kombatch.loncat.pw
.kurogaze.net
.landscapenature.pw
.larashare.com
.leechbd.tk
.leechpremium.space
.lexiit.com
.lienscash.com
.lindung.in
.link-protector.com
.link.animagz.org
.link.filmku.net
.link.im
.link.safelinkconverter.com
.link.tl
.link2dollar.com
.link2you.ru
.link4ad.com
.link5s.com
.linkajc.com
.linkarus.com
.linkbabes.com
.linkbucks.com
.linkcash.ml
.linkdecode.com
.linkdolar.xyz
.linkdrop.net
.linkpaid.net
.linkplugapp.com
.linksas.us
.linkshrink.net
.lix.in
.lnk.co
.lnk.in
.lnx.lu
.loadsanook.com
.loftlm.ru
.lolinez.com
.looble.net
.loook.ga
.looy.in
.lostpic.net
.lovechix.com
.lynk.my
.madlink.sk
.mantap.in
.manteb.in
.mantep.in
.maxmirror.com
.megaimage.org
.megaline.co
.mije.net
.minidroid.net
.miniurl.tk
.miniurls.co
.miragepics.com
.mirrorcreator.com
.mirrorupload.net
.miuitutorial.gq
.moe.god.jp
.moesubs.akurapopo.pro
.moesubs.com
.motonews.club
.motosport.pw
.mrjh.org
.mt0.org
.muucih.com
.my-link.pro
.myam.me
.myhotimage.com
.myimg.club
.myimg.info
.mylinkgen.com
.mypixxx.lonestarnaughtygirls.com
.naisho.lompat.in
.nar-04.tk
.naughtygate.net
.newimagepost.com
.nimplus.com
.nimzshare.com
.nixhelp.de
.nmac.to
.noelshack.com
.npicture.net
.nsfw.in
.nudeximg.com
.nutshellurl.com
.ohleech.com
.oload.tv
.oni.vn
.onlinepic.net
.openload.co
.ouo.io
.ouo.press
.overdream.cz
.overpic.net
.oxyl.me
.p.pw
.pasted.co
.payurl.me
.pdi2.net
.peekatmygirlfriend.com
.pengaman.link
.photo-up.info
.pic-maniac.com
.pic-money.ru
.pic-upload.de
.pic2pic.ru
.pic2pic.site
.pic2profit.com
.pic4you.ru
.pic4you.top
.pic5you.ru
.picamatic.com
.picangel.in
.picbucks.com
.piccash.net
.picexposed.com
.picfox.org
.piclambo.net
.picleet.com
.picmoe.net
.picnictrans.com
.picp2.com
.pics-money.ru
.picshare.geenza.com
.picspornfree.me
.picstream.tv
.picstwist.com
.picture-bang.net
.picturedip.com
.picturescream.asia
.picturescream.com
.pictureshoster.com
.pictureturn.com
.picturevip.com
.picz.site
.pimpandhost.com
.pir.im
.pix-link.net
.pixhost.org
.pixhub.eu
.pixliv.com
.pixroute.com
.pixsense.net
.pixsor.com
.pixup.us
.pixxx.me
.pixxxels.org
.playimg.com
.poontown.net
.pop-img.info
.pornimagex.com
.porno-pirat.ru
.pornyhost.com
.postimg.net
.postscreens.info
.preview.rlu.ru
.prntscr.com
.project-photo.net
.pronpic.org
.putlocker.com
.qaafa.com
.qqc.co
.qrrro.com
.radikal.ru
.rdlnk.co
.readthis.ca
.redirects.ca
.reducelnk.com
.reffbux.com
.repla.cr
.richlink.com
.rijaliti.info
.riurl.com
.robo.us
.ron.vn
.rqq.co
.rumahsimpel.com
.sa.ae
.safelinkconverter.com
.safelinkconverter2.com
.safelinkreview.co
.safelinkreview.com
.safelinkreviewer.com
.safelinksreview.com
.safeurl.eu
.satuasia.com
.screenlist.ru
.segmentnext.com
.sehatlega.com
.seomafia.net
.seriousdeals.net
.setlinks.us
.sexpalace.gs
.sexseeimage.com
.sexyxpixels.com
.sh.st
.shink.in
.short.am
.short.est
.shorten.id
.shortenurl.tk
.shortit.in
.shortskip.com
.shorturl.rapeit.net
.shotimg.org
.shrink-service.it
.shrink.gs
.sht.io
.sidespace.net
.similarsites.com
.sinopsisfilmku.com
.sipkur.net
.sipkur.us
.smilinglinks.com
.smll.io
.spaste.com
.sports14.pw
.srelink.com
.srnk.co
.ssl.gs
.st.oploverz.net
.st.wardhanime.net
.star-hentai.com
.stash-coins.com
.streamingfrench.net
.subirimagenes.com
.supercheats.com
.susutin.com
.sxpics.nl
.sylnk.net
.tawaku.com
.techfunda.net
.teenimage.org
.teenshot.org
.theseblogs.com
.theseforums.com
.thinfi.com
.thumbnailus.com
.tinizo.com
.tinyarrows.com
.tinylinks.co
.tinypic.com
.tl.tc
.tl7.us
.tnabucks.com
.tr5.in
.tubeviral.com
.turboimagehost.com
.typ.me
.u2ks.com
.uimgshare.com
.ulmt.in
.ulshare.net
.ultrafiles.net
.ultry.net
.ultshare.com
.unfake.it
.upan.so
.uplimg.com
.uploadimage.eu
.uploadrr.com
.upmirror.info
.url.fm
.url.ht
.url.ie
.urlbeat.net
.urlcash.com
.urlcash.net
.urlcash.org
.urle.co
.urlgalleries.com
.urlgator.com
.urlgo.gs
.urlinn.com
.urlms.com
.urlst.me
.urlv2.com
.urlwiz.com
.uskip.me
.vava.in
.vavi.co
.victly.com
.videogameblogger.com
.vidto.me
.viid.me
.viidii.info
.vir.al
.vizzy.es
.voyeurimage.org
.vvcap.net
.vzturl.com
.whackyvidz.com
.worldhack.net
.wpc8.com
.wwy.me
.wzzq.me
.x.pixfarm.net
.x45x.info
.xafox.com
.xip.ir
.xiw34.com
.xlink.me
.xt3.me
.xximg.net
.xxx.porn0day.com
.xxxhost.me
.xxximagenow.com
.xxxs.org
.xxxscreens.com
.xxxsparrow.com
.yankoimages.net
.yep.it
.yfrog.com
.yooclick.com
.youfap.me
.ysear.ch
.ysf.pl
.yyv.co
.z.gs
.zatnawqy.net
.zeljeimage.com
.zff.co
.zintata.com
.zo.mu
.zonezeedimage.com
.zpoz.net
.zytpirwai.net
.zzz.gl

#-------------------
# -

{-jsfilter}
/.*?\.js
/.*?\.css
/.*?\.dtd
/.*?\.xsd
/.*?\.json
/.*?crossdomain\.xml
TAG:^(application|text)/(x-)?javascript$

{-filter{YouTubePlus}}
.youtube.com/tv.*
.youtube.com/embed/.*
.youtube.com/live_chat.*
gaming.youtube.

{-filter{FacebookUnsponsored}}
.facebook.com/ajax/
.channel.facebook.com/.*
.facebook.com/xti.php\?.*
.facebook.com/xti.php.*
.facebook.com/ai.php\?.*
.facebook.com/ai.php.*
www.facebook.com/facebookforbusiness/
developers.facebook.com
.facebook.com/connect
.facebook.com/notifications/
.facebook.com/typeahead/