#---------------------------------------
# Initialize

{{alias}}
# Exclude all js filter
-jsfilter =  -filter{GMFunction} -filter{LongRunCPU} \
  	     -filter{CanvasBlocker} -filter{AntiSocialLocker} -filter{GreasyForkjs} -filter{Openload-JS}  \
	     -filter{EnableRightClick} -filter{NoOpener} \
	     -filter{YoutubeHD} -filter{BypassYouTubeAge} \
	     -filter{MaknyosAutoIn} -filter{AdsBypass} \
	     -filter{FacebookUnsponsored} -filter{TwitchAds} \
	     -filter{MangaLoaderNSFW} -filter{MangaLoader}

#---------------------------------------
# Global

#-------------------
# +


#-------------------
# -


#---------------------------------------
# Specific

#-------------------
# +

{+filter{CanvasBlocker}}
#/

{+filter{GreasyForkjs}}
.greasyfork.org/.*?\.js

{+filter{GMFunction} +filter{EnableRightClick}}
.exhentai.org
.readlightnovel.org
.webnovelonline.com
.webtruyen.com
.manhuagui.com

{+filter{YoutubeHD}}
.youtube.com

{+filter{YouTubeJSEngineTamer}}
#.youtube.com

{+filter{YoutubeAds}}
.youtube.com

{+filter{BypassYouTubeAge}}
.youtube.com

{+filter{GMFunction} +filter{FacebookHideSponsored}}
.facebook.com

{+filter{twitterads}}
#.twitter.com

{+filter{RedditPromo}}
.reddit.com

{+filter{CloseTwitchAds}}
.twitch.tv

{+filter{NoOpener}}
#/

{+filter{GMFunction} +filter{MangaLoader}}
.bato.to/reader.*
.mangafox.me/manga/
.mangafox.la/manga/
.fanfox.net/manga/
.readms.net/r/
.readms.net/read/
.mangastream.com/r/
.mangastream.com/read/
.mangareader.net/
.mangahere.co/manga/
.mangahere.cc/manga/
.mangapanda.com/
.mangapark.me/manga/
.mngcow.co/
.centraldemangas.org/online/
.com.br/leitura/online/capitulo/
.mangatown.com/manga/
.manga-joy.com/
.dm5.com/m.*
.senmanga.com/
.japscan.com/lecture-en-ligne/
.pecintakomik.com/manga/
.mangawall.com/manga/
.manga.animea.net/
.kissmanga.com/Manga/
.view.thespectrum.net/series/
.manhua.dmzj.com/
.hqbr.com.br/hqs//capitulo//leitor/0
.dmzj.com/view/
.mangaindo.id/
.mangadoom.co/
.mangago.me/read-manga/
.mangalator.ch/show.php\?gallery=.*
.eatmanga.com/Manga-Scan/
.mangacat.me?
.mangahen.com/
.readmng.com/
.mangatraders.biz/read-online/
.mangainn.net/manga/chapter/
.kukudm.com/comiclist/
.mangamap.com/
.mangachapter.me/
.kawaii.ca/reader/
.lonemanga.com/manga/
.read.egscans.com/om/manga/
.manga.madokami.al/reader/
.read.egscans.com/
.imperialscans.com/read/
.chuixue.com/manhua/
.sh-arab.com/manga/
.spinybackmanga.com/
.br.mangahost.com/manga/
.manga.ae/
.mangaforall.com/manga/
.hellocomic.com/
.3asq.info/
.readcomiconline.to/Comic/
.moonbunnycafe.com/
.mangaeden.com/
.comicastle.org/read-.*
.mymh8.com/chapter/
.unionmangas.net/leitor/
.otakusmash.com/
.mangahome.com/manga/
.readcomics.tv
.cartoonmad.com/comic/
.comicnad.com/comic/
.ikanman.com/comic/
.manhuagui.com/comic/
.mangasail.com/
.mangatail.com/
.titaniascans.com/reader/
.komikstation.com?
.gmanga.me/mangas?
.mangadex.org/chapter/
.merakiscans.com/
.biamamscans.com/read/
.read.lhtranslation.com/.html
.930mh.com/manhua/
.mangabox.me/reader//episodes/
.twocomic.com/view/comic_.*.html\?ch=.*
.manga.redhawkscans.com/reader/read/
.reader.s2smanga.com/read/
.casanovascans.com/read/
.reader.vortex-scans.com/read/
.reader.roseliascans.com/read/
.mangatopia.net/slide/read/
.twistedhelscans.com/read/
.sensescans.com/reader/read/
.reader.kireicake.com/read/
.substitutescans.com/reader/read/
.mangaichiscans.mokkori.fr/fs/read/
.reader.shoujosense.com/read/
.friendshipscans.com/slide/read/
.manga.famatg.com/read/
.demonicscans.com/FoOlSlide/read/
.reader.psscans.info/read/
.otscans.com/foolslide/read/
.necron99scans.com/reader/read/
.manga.inpowerz.com/read/
.reader.evilflowers.com/read/
.reader.cafeconirst.com/read/
.kobato.hologfx.com/reader/read/
.abandonedkittenscans.mokkori.fr/reader/read/
.jaiminisbox.com/reader/read/
.gomanga.co/reader/read/
.reader.manga-download.org/read/
.manga-ar.net/manga?
.helveticascans.com/r/read/
.reader.thecatscans.com/read/
.yonkouprod.com/reader/read/
.reader.championscans.com/read/
.reader.whiteoutscans.com/read/
.hatigarmscans.eu/hs/read/
.lector.kirishimafansub.com/lector/read/
.hotchocolatescans.com/fs/read/
.slide.world-three.org/read/

{+filter{GMFunction} +filter{MangaLoaderNSFW}}
dynasty-scans.com/chapters/
hentaifr.net
prismblush.com/comic/
www.hentairules.net/galleries.*/picture.php.*
pururin.us/read/
hitomi.la/reader/
.doujins.com
www.8muses.com/comix/picture/
nowshelf.com/watch/
.nhentai.net/g/
.nhentai.to/g/
e-hentai.org/s/
exhentai.org/s/
www.fakku.net/.*/.*/read.*
hentaihere.com/m/
www.hentaihere.com/m/
.tsumino.com/Read/View/
www.hentaibox.net
.hentai-free.org
.mangafap.com/image/
.hentai4manga.com/hentai_manga/
.heymanga.me/manga/
.simply-hentai.com/.*/page/
.gameofscanlation.moe/projects/
.luscious.net/c/.*/pictures/album/.*/id/
.hentaifox.com/g/
.hentai2read.com
.hentai.ms/manga/
reader.yuriproject.net/read/
ecchi.japanzai.com/read/
h.japanzai.com/read/
reader.japanzai.com/read/
yomanga.co/reader/read/
raws.yomanga.co/read/
hentai.cafe/manga/read/
.yuri-ism.net/slide/read/

#-------------------
# -

{-jsfilter}
TAG:^(application|text)/(x-)?javascript$

{-filter{CanvasBlocker}}
.facebook.com
.regex101.com
.blogtruyen.vn
.twist.moe
.phimmoi*.net
.hltv.org
.voz.vn
.horriblesubs.info
.90p.tv
.sap.com
.tinhte.vn
.reddit.com
nhentai.net
.google.com/maps/
.twitch.tv

{-filter{FacebookUnsponsored}}
.facebook.com/ajax/
.channel.facebook.com/.*
.facebook.com/xti.php\?.*
.facebook.com/xti.php.*
.facebook.com/ai.php\?.*
.facebook.com/ai.php.*
www.facebook.com/facebookforbusiness/
developers.facebook.com
.facebook.com/connect
.facebook.com/notifications/
.facebook.com/typeahead/

{-filter{FacebookUnsponsored2}}
.facebook.com/privacy/.*
.facebook.com/settings/.*
.facebook.com/marketplace/.*