#---------------------------------------
# Specifiction site

{+filter{ads} +filter{ads2}}
#.miui.vn

{+filter{popunder}}
.truyentranhtuan.com
.blogtruyen.
.vechai.
.truyentranh8.
.manga24h.
.hamtruyen.
.dammetruyen.
.animetvn.

{+filter{disableDHTML}}
.24h.com.vn

{+filter{vns}}
.vnsharing.

{+filter{vozforums}}
vozforums.com

{+filter{blogtruyen}}
.blogtruyen.com

{+filter{manga24h}}
.manga24h.

{+filter{truyentranhtuan}}
.truyentranhtuan.com

{+filter{nyaa}}
.nyaa.se

{+filter{youtube}}
.youtube.

{+filter{kiss}}
.kissmanga.com
.kissanime.
.kisscartoon.me
.kisshentai.net

{+filter{openload}}
.openload.

{+filter{h-ani}}
.hanime.tv

{+filter{mangadeer}}
.mangadeer.com
.mangapark.com
.mangawindow.com
.mangapark.me

{+filter{mangareader}}
.mangareader.

{+filter{izmanga}}
.izmanga.
.iztruyentranh.

{+filter{mangafox}}
.mangafox.

{+filter{pixiv}}
.pixiv.net

{+filter{deviantart}}
.deviantart.com

{+filter{xda}}
.xda-developers.com

{+filter{miui-vn}}
.miui.vn

{+filter{softpedia}}
.softpedia.com

{+filter{tuoitre}}
.tuoitre.vn

{+filter{dantri}}
.dantri.com.vn

{+filter{vietnamnet}}
.vietnamnet.vn

{+filter{vnexpress}}
.vnexpress.net

{+filter{hdvn}}
.hdvietnam.com

{+filter{aeria}}
.aeriagames.com

{+filter{mediafire}}
.mediafire.com

{+filter{game8}}
.game8.

{+filter{senmanga}}
.senmanga.com

{+filter{24h}}
.24h.com.vn

{+filter{bongdaso}}
.bongdaso.com

{+filter{up4share}}
.4share.vn

{+filter{hamtruyen}}
.hamtruyen.

{+filter{mangak}}
.mangak.

{+filter{truyentranh8}}
.truyentranh8.

{+filter{mobitruyen}}
.truyen.hay.
.mobitruyen.

{+filter{webtruyen}}
.webtruyen.com

{+filter{truyentranh}}
.truyentranh.net

{+filter{ani47}}
.anime47.com

{+filter{photobucket}}
.photobucket.

{+filter{kickass}}
.kickass.

{+filter{tinhte}}
.tinhte.

{+filter{dm5}}
.dm5.

{+filter{muachung}}
.muachung.vn

{+filter{xemvn}}
.xem.vn

{+filter{phim-media}}
.phim.media

{+filter{hayhaytv}}
.hayhaytv.vn

{+filter{vnreview}}
.vnreview.

{+filter{pose}}
pose.com.vn

{+filter{gg}}
.google.com.vn
.google.com

{+filter{chiasenhac}}
chiasenhac.com

{+filter{closers}}
closershq.com

{+filter{facebook}}
.facebook.com

{+filter{vast.xml}}
/vast.xml

{+filter{fakku}}
.fakku.net

{+filter{sankaku}}
.sankakucomplex.com

{+filter{horriblesubs}}
horriblesubs.info

{+filter{anticlickjacking}}
www.clickjack.net

{+filter{adtimaserver} +force-text-mode}
api.adtimaserver.vn/zad/

{+filter{greasyfork}}
.greasyfork.org

{+filter{fptplay}}
play.fpt.vn
fptplay.net

{+filter{talk-tv}}
.csmtalk.vcdn.vn
talktv.vn

{+filter{secufiles}}
.secufiles.com

#---------------------------------------
# -
{-filter{facebook}}
.facebook.com/video/liveviewcount/
.facebook.com/chat/user_info/
.facebook.com/ajax/
.facebook.com/notifications/
.facebook.com/typeahead/