#----------------------------------------------------------------------------
# Specific settings

#-------------------------------------------------------
{+filter{Global-Filter-------------------}}
# Global filter

{+filter{ads} +filter{ads2}}
.valvrareteam.com
.vetv.vn

{+filter{popunder}}
.truyentranhtuan.com
.blogtruyen.
.vechai.
.truyentranh8.
.manga24h.
.hamtruyen.
.truyensieuhay.
.dammetruyen.
.animetvn.
.truyenqq.

{+filter{disableDHTML}}
.24h.com.vn

{+filter{anticlickjacking}}
www.clickjack.net

{+filter{canvas}}
browserleaks.com

#---------------------------------------
# Specifiction site

#-------------------------
{+filter{Animu-------------------------}}
#Animu

#-------------
{+filter{Misc-------------}}
#Misc

{+filter{vns}}
.vnsharing.

{+filter{mal}}
.myanimelist.

{+filter{ann}}
.animenewsnetwork.com

{+filter{sankaku}}
.sankakucomplex.com

{+filter{nyaa}}
.nyaa.se

{+filter{horriblesubs}}
horriblesubs.info

#-------------
{+filter{MangaVN-------------}}
#MangaVN

{+filter{blogtruyen}}
.blogtruyen.
.blogtruyenmoi.

{+filter{manga24h}}
.manga24h.

{+filter{truyentranhtuan}}
.truyentranhtuan.com

{+filter{truyenqq}}
.truyenqq.

{+filter{nettruyen}}
.nettruyen.com
.nhattruyen.com
.nettruyen*.com
.nhattruyen*.com

{+filter{truyentranhlh}}
.truyentranhlh.

{+filter{hamtruyen}}
.hamtruyen.
.truyensieuhay.

{+filter{truyentranh8}}
.truyentranh8.
.truyentranhtam.

{+filter{mobitruyen}}
.truyen.hay.
.mobitruyen.

{+filter{truyentranh}}
.truyentranh.net

{+filter{academy}}
.academyvn.
.hocvientruyentranh.

{+filter{otakusan}}
.otakusan.net
.otakuscan.net

{+filter{izmanga}}
.izmanga.
.iztruyentranh.

{+filter{mangak}}
.mangak.

{+filter{commicvn}}
.comicvn.net

{+filter{truyentranhaudio}}
.truyentranhaudio.
.vcomic.net

#-------------
{+filter{Manga-------------}}
#Manga

{+filter{kiss}}
.kissmanga.com
.kissanime.
.kisscartoon.me
.kisshentai.
.kissdoujin.

{+filter{batoto}}
.bato.to

{+filter{mangadeer}}
.mangadeer.com
.mangapark.com
.mangawindow.com
.mangapark.me

{+filter{senmanga}}
.senmanga.com

{+filter{mangafox}}
.mangafox.

{+filter{mangareader}}
.mangareader.

{+filter{mangakakalot}}
.mangakakalot.
.manganelo.
.readmanganato.

{+filter{mangadex}}
.mangadex.

{+filter{mangarock}}
.mangarock.

{+filter{mangahere}}
.manga-here.club

{+filter{mangatail}}
.mangatail.

{+filter{lhmanga}}
.lhscan.net
.loveheaven.net

{+filter{dm5}}
.dm5.

{+filter{mangaraw}}
.mangaraw.

#-------------
{+filter{MangaH-------------}}
#MangaH

{+filter{h-ani}}
.hanime.tv
.hentaiz.net

{+filter{hitomi}}
.hitomi.la

{+filter{nht}}
.nhentai.
.hentaivn.

{+filter{h2r}}
.hentai2read.

{+filter{fakku}}
.fakku.net

#-------------
{+filter{Anime-------------}}
#Anime

{+filter{ani47}}
.anime47.com

{+filter{animetvn}}
.animetvn.tv

#-------------
{+filter{Novel-------------}}
#Novel

{+filter{hako}}
.hako.re
.docln.net

{+filter{readln}}
.readlightnovel.

{+filter{webnovel}}
.webnovelonline.com

{+filter{asianhobbyist}}
.asianhobbyist.com

{+filter{valvrareteam}}
.valvrareteam.com

{+filter{webtruyen}}
.webtruyen.
.dtruyen.

{+filter{truyenfull}}
.truyenfull.
.sstruyen.
.8cache.com

{+filter{bachngocsach}}
.bachngocsach.

{+filter{truyenconect}}
.truyenconect.

{+filter{metruyenchu}}
.metruyenchu.

{+filter{isotls}}
.isotls.

{+filter{kaystls}}
.kaystls.

{+filter{zetrotranslation}}
.zetrotranslation.

#-------------------------
{+filter{Techs-------------------------}}
#Techs

{+filter{gg}}
.google.com.vn
.google.com

{+filter{notebookcheck}}
.notebookcheck.net

{+filter{softpedia}}
.softpedia.com

{+filter{ghacks}}
.ghacks.net

{+filter{vnreview}}
.vnreview.

{+filter{greasyfork}}
.greasyfork.org

{+filter{techtalk}}
.techtalk.vn

{+filter{khoahoc}}
.khoahoc.tv

{+filter{quantrimang}}
.quantrimang.

#-------------------------
{+filter{News-------------------------}}
#News

{+filter{tuoitre}}
.tuoitre.vn

{+filter{dantri}}
.dantri.com.vn

{+filter{vietnamnet}}
.vietnamnet.vn

{+filter{vnexpress}}
.vnexpress.net

{+filter{vnexpress-video}}
.vnecdn.net

{+filter{thanhnien}}
.thanhnien.vn

{+filter{genk}}
.genkcdn.vn/web_js/
.genk.

{+filter{tinhte}}
.tinhte.

{+filter{24h}}
.24h.com.vn

{+filter{bongdaso}}
.bongdaso.
.bongdaso*.

{+filter{bongdaf}}
.bongdaf.
.ngoac.tv

{+filter{pose}}
pose.com.vn

{+filter{bongda365}}
.bongda365.club

#-------------------------
{+filter{Socials-------------------------}}
#Socials

{+filter{facebook}}
.facebook.com

{-filter{facebook}}
.facebook.com/video/liveviewcount/
.facebook.com/chat/user_info/
.facebook.com/ajax/
.facebook.com/notifications/
.facebook.com/typeahead/

{+filter{twitter}}
.twitter.
.x.com

{+filter{youtube}}
.youtube.

{+filter{4chan}}
.4chan.org
.4channel.
.4cdn.org

{+filter{pixiv}}
.pixiv.net

{+filter{deviantart}}
.deviantart.com

{+filter{wikia}}
.wikia.com
.fandom.com

{+filter{reddit}}
.reddit.com

#-------------------------
{+filter{Forums-----------------------}}
#Forums

{+filter{vozforums}}
vozforums.com
.voz.vn

{+filter{xda}}
.xda-developers.com
.xdaforums.com

{+filter{miui-vn}}
.miui.vn

{+filter{xiaomieu}}
.xiaomi.eu

{+filter{hdvn}}
.hdvietnam.com
.hdvietnam.me

{+filter{ankulua}}
ankulua.boards.net

{+filter{xamvn}}
.xamvn.

{+filter{otofun}}
.otofun.net

#-------------------------
{+filter{Media-------------------------}}
#Media

{+filter{90phut}}
.90phut.
.90phut*.
.90m.
.90p.
.binhluanvidamme.
.binhluanvidamme*.
.binhluan.vip
.phut91.
.phut90.
.tiengruoi.
.1gio30phut.
90.*.link
mitom.*.link
mitom*.*.link
.thapcam.

{+filter{90phuthd}}
.tructiepeuro.live
.bongdahomnay.live
.vebotv.

{+filter{90p-js}}
.90phut*.live/js/mt/app.*.js
.vebo.*/js/app.*.js
.90pcdn.*/js/app.*.js
.90pcdn.*/js/mt/app.*.js

{+filter{90p-pl}}
.4shares.live

{+filter{thapcam-js}}
.thapcam.net/.*/*.js?

{+filter{cbox}}
www6.cbox.ws

{+filter{xemvn}}
.xem.vn

{+filter{phim-media}}
.phim.media

{+filter{hayhaytv}}
.hayhaytv.vn

{+filter{phimmoi}}
.phimmoi.net
.phimmoi*.net
.zphimmoi.
.phimmoii.

{+filter{vungtv}}
.vung.tv
.hatde.tv

{+filter{photobucket}}
.photobucket.

{+filter{chiasenhac}}
chiasenhac.com

{+filter{talk-tv}}
.csmtalk.vcdn.vn
talktv.vn

{+filter{bilutv}}
.bilutv.com

{+filter{fptplay}}
play.fpt.vn
fptplay.net
fptplay.vn

{+filter{dongphym}}
.dongphym.net

{+filter{tivivip}}
.xemtivivip.

{+filter{phimhdvn}}
.phimhdvn.net

{+filter{vkool}}
.vkoolz.net

{+filter{mphimmoi}}
.mphimmoi.
.mphimmoitv.

#-------------------------
{+filter{Games-------------------------}}
#Games

{+filter{twitch}}
.twitch.
.twitchcdn.net/.*.js

{+filter{garena}}
garena.live

{+filter{game8}}
.game8.

{+filter{gametv}}
.gametv.

{+filter{hltv}}
.hltv.org

{+filter{aeria}}
.aeriagames.com

{+filter{closers}}
closershq.com

#-------------------------
{+filter{Shoppings-------------------}}
#Shoppings

{+filter{memoryzone}}
.memoryzone.

{+filter{hnc}}
.hanoicomputer.vn

{+filter{muachung}}
.muachung.vn

#-------------------------
{+filter{Downloads------------------}}
#Downloads

{+filter{mediafire}}
.mediafire.com

{+filter{up4share}}
.4share.vn

{+filter{fshare}}
.fshare.vn

{+filter{kickass}}
.kickass.

{+filter{secufiles}}
.secufiles.com

{+filter{shink}}
.shink.in

{+filter{openload}}
.openload.

{+filter{1337x}}
.1337x.to

#-------------------------
{+filter{Others------------------------}}
#Others

{+filter{vcmedia}}
.vcmedia.vn

{+filter{rapidvideo}}
.rapidvideo.

{+filter{adtimaserver} +force-text-mode}
api.adtimaserver.vn/zad/

#-------------------------