#---------------------------------------
# Specifiction site

{+filter{ads} +filter{ads2}}
#.miui.vn
.valvrareteam.com
.vetv.vn

{+filter{UTF-8}}
.xda-developers.com

{+filter{popunder}}
.truyentranhtuan.com
.blogtruyen.
.vechai.
.truyentranh8.
.manga24h.
.hamtruyen.
.truyensieuhay.
.dammetruyen.
.animetvn.
.truyenqq.

{+filter{disableDHTML}}
.24h.com.vn

{+filter{vns}}
.vnsharing.

{+filter{hako}}
.hako.re

{+filter{vozforums}}
vozforums.com
.voz.vn

{+filter{blogtruyen}}
.blogtruyen.

{+filter{manga24h}}
.manga24h.

{+filter{academy}}
.academyvn.
.hocvientruyentranh.

{+filter{truyentranhtuan}}
.truyentranhtuan.com

{+filter{nyaa}}
.nyaa.se

{+filter{4chan}}
.4chan.org
.4cdn.org

{+filter{youtube}}
.youtube.

{+filter{kiss}}
.kissmanga.com
.kissanime.
.kisscartoon.me
.kisshentai.
.kissdoujin.

{+filter{batoto}}
.bato.to

{+filter{openload}}
.openload.

{+filter{h-ani}}
.hanime.tv

{+filter{hitomi}}
.hitomi.la

{+filter{nht}}
.nhentai.
.hentaivn.

{+filter{h2r}}
.hentai2read.

{+filter{mal}}
.myanimelist.

{+filter{mangatail}}
.mangatail.

{+filter{mangadeer}}
.mangadeer.com
.mangapark.com
.mangawindow.com
.mangapark.me

{+filter{mangareader}}
.mangareader.

{+filter{izmanga}}
.izmanga.
.iztruyentranh.

{+filter{mangafox}}
.mangafox.

{+filter{mangarock}}
.mangarock.

{+filter{mangadex}}
.mangadex.

{+filter{mangakakalot}}
.mangakakalot.
.manganelo.

{+filter{truyentranhlh}}
.truyentranhlh.

{+filter{pixiv}}
.pixiv.net

{+filter{deviantart}}
.deviantart.com

{+filter{xda}}
.xda-developers.com

{+filter{miui-vn}}
.miui.vn

{+filter{xiaomieu}}
.xiaomi.eu

{+filter{notebookcheck}}
.notebookcheck.net

{+filter{softpedia}}
.softpedia.com

{+filter{reddit}}
.reddit.com

{+filter{wikia}}
.wikia.com

{+filter{tuoitre}}
.tuoitre.vn

{+filter{dantri}}
.dantri.com.vn

{+filter{vietnamnet}}
.vietnamnet.vn

{+filter{vnexpress}}
.vnexpress.net

{+filter{vnexpress-video}}
.vnecdn.net

{+filter{genk}}
.genkcdn.vn/web_js/

{+filter{garena}}
garena.live

{+filter{hdvn}}
.hdvietnam.com

{+filter{aeria}}
.aeriagames.com

{+filter{mediafire}}
.mediafire.com

{+filter{game8}}
.game8.

{+filter{gametv}}
.gametv.

{+filter{vcmedia}}
.vcmedia.vn

{+filter{hltv}}
.hltv.org

{+filter{senmanga}}
.senmanga.com

{+filter{24h}}
.24h.com.vn

{+filter{bongdaso}}
.bongdaso.com

{+filter{bongdaf}}
.bongdaf.
.ngoac.tv

{+filter{90phut}}
.90phut.
.90m.tv

{+filter{hltv}}
.hltv.org

{+filter{up4share}}
.4share.vn

{+filter{hamtruyen}}
.hamtruyen.
.truyensieuhay.

{+filter{mangak}}
.mangak.

{+filter{commicvn}}
.comicvn.net

{+filter{truyentranh8}}
.truyentranh8.
.truyentranhtam.

{+filter{mobitruyen}}
.truyen.hay.
.mobitruyen.

{+filter{webtruyen}}
.webtruyen.com

{+filter{truyenfull}}
.truyenfull.
.sstruyen.

{+filter{truyentranh}}
.truyentranh.net

{+filter{truyenqq}}
.truyenqq.

{+filter{lhmanga}}
.lhscan.net

{+filter{valvrareteam}}
.valvrareteam.com

{+filter{animetvn}}
.animetvn.tv

{+filter{ani47}}
.anime47.com

{+filter{photobucket}}
.photobucket.

{+filter{kickass}}
.kickass.

{+filter{tinhte}}
.tinhte.

{+filter{dm5}}
.dm5.

{+filter{muachung}}
.muachung.vn

{+filter{xemvn}}
.xem.vn

{+filter{phim-media}}
.phim.media

{+filter{hayhaytv}}
.hayhaytv.vn

{+filter{phimmoi}}
.phimmoi.net

{+filter{vungtv}}
.vung.tv

{+filter{vnreview}}
.vnreview.

{+filter{pose}}
pose.com.vn

{+filter{gg}}
.google.com.vn
.google.com

{+filter{twitter}}
.twitter.

{+filter{twitch}}
.twitch.
.twitchcdn.net/.*.js

{+filter{chiasenhac}}
chiasenhac.com

{+filter{closers}}
closershq.com

{+filter{facebook}}
.facebook.com

{+filter{vast.xml}}
/vast.xml

{+filter{fakku}}
.fakku.net

{+filter{sankaku}}
.sankakucomplex.com

{+filter{horriblesubs}}
horriblesubs.info

{+filter{rapidvideo}}
.rapidvideo.

{+filter{anticlickjacking}}
www.clickjack.net

{+filter{adtimaserver} +force-text-mode}
api.adtimaserver.vn/zad/

{+filter{greasyfork}}
.greasyfork.org

{+filter{fptplay}}
play.fpt.vn
fptplay.net
fptplay.vn

{+filter{fshare}}
.fshare.vn

{+filter{talk-tv}}
.csmtalk.vcdn.vn
talktv.vn

{+filter{bilutv}}
.bilutv.com

{+filter{secufiles}}
.secufiles.com

{+filter{shink}}
.shink.in

#---------------------------------------
# -
{-filter{facebook}}
.facebook.com/video/liveviewcount/
.facebook.com/chat/user_info/
.facebook.com/ajax/
.facebook.com/notifications/
.facebook.com/typeahead/