#---------------------------------------
# Global

{+filter{savemyeyes}}
#/

#---------------------------------------
# Specific

{+filter{FacebookStyle}}
#.facebook.com

{+filter{GoogleHestiaStyle}}
#.google.

{+filter{gg-new-style}}
#www.google.

{+filter{FacebookStyle2}}
#.facebook.com

{+filter{FacebookStyle3}}
#.facebook.com

#---------------------------------------
# -
{-filter{FacebookStyle2}}
.facebook.com/video/liveviewcount/
.facebook.com/chat/user_info/
.facebook.com/ajax/
.facebook.com/notifications/
.facebook.com/typeahead/

{-filter{gg-new-style}}
sites.google.com